### ISSUE TITLE
dataframe row names

### ISSUE THREAD

**Issue by stla** [jeroen/jsonlite#165]
Hello,

According to `?toJSON`, the arguments in the ellipsis (`...`) are passed to the `print` function.

Therefore I expected not to get the key `_row` in the example below, but it is there:

```
> dat <- mtcars[1:2,1:2]
> jsonlite::toJSON(dat, row.names=FALSE)
[{"mpg":21,"cyl":6,"_row":"Mazda RX4"},{"mpg":21,"cyl":6,"_row":"Mazda RX4 Wag"}]
```

Is it expected ? In this case, that's me who misunderstand.

**Comment by jeroen** [comment]
The argument is called `rownames`:

```r
dat <- mtcars[1:2,1:2]
jsonlite::toJSON(dat, rownames=FALSE)
```

Perhaps `row.names` would have been better for consistency indeed.
