### ISSUE TITLE
Converting numeric values in the range of e-5 returns 0 in some circumstances

### ISSUE THREAD

**Issue by Ben-Cossins** [jeroen/jsonlite#166]
I ran into an issue when converting data from some experiments into json format in order to create an interactive graphs. further exploration revealed that some of the data being exported to json was resulting in NaN errors in javascript. when I looked at the json data directly it was converting certain values to 0, and all those were datapoints in the range of e-5, with values either side being fine.

using the further arguments of "digits = NA" resolved it and provided correct results, and in trying to provide dummy data that would recreate this have found that it isnt the most consistent.

some data frames with e-5 were correctly converted, whilst others weren't (as shown in example data) 

details of commands used:
```
test <- read.csv("test.csv", header = TRUE)
toJSON(test, pretty = TRUE)
```
example output
>   {
    "Variable1": "d",
    "value1": 0.0001,
    "value2": 0.0016,
    "Variable2": "ENSMUSG00000000004"
  },
  {
    "Variable1": "e",
    "value1": **0**,
    "value2": 0.0003,
    "Variable2": "ENSMUSG00000000005"
  },
  {
    "Variable1": "f",
    "value1": 1.22e-06,
    "value2": 0.0001,
    "Variable2": "ENSMUSG00000000006"
  },

system details
> sessionInfo()
R version 3.2.3 (2015-12-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.1 LTS
locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C               LC_TIME=en_GB.UTF-8        LC_COLLATE=en_GB.UTF-8     LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_GB.UTF-8   
 [7] LC_PAPER=en_GB.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C       
attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     
other attached packages:
[1] jsonlite_1.2

loaded via a namespace (and not attached):
[1] tools_3.2.3

tried attaching the file, but keep hitting errors, therefore pasting it in (comma separated values(

Variable1,value1,value2,Variable2
a,1.22E-01,2.00E-01,ENSMUSG00000000001
,1.22E-02,4.00E-02,ENSMUSG00000000002
c,1.22E-03,8.00E-03,ENSMUSG00000000003
d,1.22E-04,1.60E-03,ENSMUSG00000000004
e,1.22E-05,3.20E-04,ENSMUSG00000000005
f,1.22E-06,6.40E-05,ENSMUSG00000000006
g,1.22E-07,1.28E-05,ENSMUSG00000000007
h,1.22E-08,2.56E-06,ENSMUSG00000000008
I,1.22E-09,5.12E-07,ENSMUSG00000000009
j,1.22E-10,1.02E-07,ENSMUSG00000000010
k,1.22E-11,2.05E-08,ENSMUSG00000000011
l,1.22E-12,4.10E-09,ENSMUSG00000000012
m,1.22E-13,8.19E-10,ENSMUSG00000000013
n,1.22E-14,1.64E-10,ENSMUSG00000000014

**Comment by jeroen** [comment]
The default in `toJSON` rounds to 4 **decimal digits**. Try one of these:

```r
toJSON(test, digits = NA, pretty = TRUE)
```

```r
toJSON(test, pretty = TRUE, use_signif = TRUE)
```

**Comment by pilare** [comment]
@jeroen I've came up on that issue while using openCPU. Is there a way to configure openCPU to use use_signif = TRUE by default? So I won't have discrepancies between /R/.val/print and /R/.val/json output.

**Comment by jeroen** [comment]
You can append the `toJSON` arguments as http parameters to the `/json` URL in opencpu:

https://cloud.opencpu.org/ocpu/tmp/x0ef3399162d21a/R/.val/json?digits=2&use_signif=true

**Comment by pilare** [comment]
Thank you @jeroen. Your solution will work for us, although I need to go through my calls to json files in my code and modify slightly node-opencpu package. Is there a way to set this globally for openCPU server? Maybe using: Renviron or Rprofile files? We are also looking for a solution so I will add it here or to opencpu mailing list if we find one.
