### ISSUE TITLE
Error: No method asJSON S3 class: zoo

### ISSUE THREAD

**Issue by misteliy** [jeroen/jsonlite#168]
Would be nice to be able to directly write a zoo or xts object.

**Comment by jeroen** [comment]
I am not familiar with these classes well enough to know what their structure looks like and what would be good json encoding. From the examples it seem like a `zoo` object might be many things (factor, matrix, named vector, ...).

I think you're better manually coercing the object yourself:

```r
toJSON(as.data.frame(object))
```

```r
toJSON(as.matrix(object))
```

**Comment by apampana** [comment]
is this problem solved? I am getting same results when trying to convert ensemble builts from grch 38 to 37.
