### ISSUE TITLE
NA encoded differently depending on which NA you use

### ISSUE THREAD

**Issue by madeleine-empirical** [jeroen/jsonlite#169]
I am using jsonlite 1.2 on R 3.3.2 on Ubuntu 16.04.

By default, NA is encoded differently depending on which NA you use:

```
> library(jsonlite)
> toJSON(list(1, NA_character_, 3), auto_unbox=TRUE)
[1,null,3] 
> toJSON(list(1, NA_real_, 3), auto_unbox=TRUE)
[1,"NA",3] 
```

This is alluded to in the `toJSON` help, but it's confusing, and it took me a while to figure out what was going on, because it leads to the following confusing behavior:
```
> toJSON(as.list(c(1, NA, 3)), auto_unbox=TRUE)
[1,"NA",3] 
> toJSON(list(1, NA, 3), auto_unbox=TRUE)
[1,null,3] 
```
where `as.list(c(1, NA, 3))` and `list(1, NA, 3)` have the same printed representation.

Thanks for considering this.

**Comment by jeroen** [comment]
This is explained in the [jsonlite paper](https://arxiv.org/abs/1403.2805) section 2.1.1. You can override the defaults with the 'na' parameter in toJSON.
