### ISSUE TITLE
consider option for append=TRUE in write_json?

### ISSUE THREAD

**Issue by cboettig** [jeroen/jsonlite#181]
of course one can work around this by just building the list up in R first with toJSON, but just an idea to think about for consistency with other write_ methods?

**Comment by jeroen** [comment]
I don't think this makes sense for JSON. For csv you can append two datasets together and the result is still csv. For JSON the concatenation of two json strings can never be valid JSON.

Do you have a specific use case in mind that requires appending? Are you aware of `stream_out` which writes lines of json records to a connection?

Note that it is possible already to append by opening the file in append mode:

```r
tmp <- tempfile()
writeLines("This is a test", tmp)

con <- file(tmp, "a+")
jsonlite::write_json(list(foo="bar"), con)
close(con)

readLines(tmp)
```

**Comment by cboettig** [comment]
Good point. I was thinking it could wrap in `[]` but that clearly isn't just appending
