### ISSUE TITLE
Headers lost when using toJSON

### ISSUE THREAD

**Issue by wakJoseph945** [jeroen/jsonlite#183]
I am using `toJSON(data, dataframe='values',pretty=TRUE)` to convert a dataframe to JSON type in R, but the headers are lost in this process. 
`year<-c('2014','2015','2016','2017')
Sales<-c(1000,1170,660,1030)
Expenses<-c(400,460,1120,540)
Profit<-c(200,250,300,350)
data<-data.frame(year,Sales,Expenses,Profit)`

And after using toJSON:
`x<-toJSON(data, dataframe='values',pretty=TRUE)
> print(x)
[
  ["2014", 1000, 400, 200],
  ["2015", 1170, 460, 250],
  ["2016", 660, 1120, 300],
  ["2017", 1030, 540, 350]
] `

  While in Google.visualization, the headers are needed to load the data. Is there a command in jsonlite that can keep the headers?

**Comment by jeroen** [comment]
Well that' precisely the meaning of of `dataframe = 'values'`. If you remove this argument, each value in the output has the corresponding column in the key.

Maybe one of these work for you:

```r
x <- toJSON(data, pretty = TRUE)
```

Or:
```r
x <- toJSON(list(names = names(data), data = data), dataframe = 'values')
```
