### ISSUE TITLE
"lexical error: invalid string in json text." when the file simply not exist

### ISSUE THREAD

**Issue by hannarud** [jeroen/jsonlite#202]
It may be really confusing:

Example:
I have a file named `"test_new.json"`.

when I try to `fromJSON("test_new.json")` everything is read-in, of course.
If I misspell the file name,  for example, try `fromJSON("test_neww.json")` I get an error like

```
Error: lexical error: invalid string in json text.
                                       test_neww.json
                     (right here) ------^
```

But that's definitely not a spelling error, file just don't exist. It is really confusing.

**Comment by jeroen** [comment]
That is corerct; if the file doesn't exist, `fromJSON` will try to parse the text as literal json.

**Comment by hannarud** [comment]
Oh, got it. I still find this confusing, but see the reason now. But no objections as it is done by design.
