### ISSUE TITLE
Please support encoding options in `write_json`

### ISSUE THREAD

**Issue by psychelzh** [jeroen/jsonlite#207]
I found that there is no options to choose an encoding, e.g. `UTF-8`, when using `write_json` to store a `list` or `data.frame`. Will it be supported?

**Comment by jeroen** [comment]
JSON is `utf-8` by definition. What sort of option would you like?

**Comment by RobertMyles** [comment]
I have a problem that seems related, maybe you could shed some light on it please, @jeroen? I have some .txt files that somebody else has prepared. To me, they look like JSON, only with a .txt suffix. Here's an example of the first few lines: 

```
{
  "status": "DONE",
  "reference": "d88bc970-e727",
  "operating_mode": "accurate",
  "statistics": {
    "request_processing_time": 1979,
    "content_fetch_time": [
      1968
    ],
    "job_preparation_time": 0,
    "audio_analysis_time": 0,
    "segmentation_time": 3219,
    "merge_time": 609,
    "formatting_time": 218
  },
```

I'm reading these into R with `from_json()` without any problems. When I save them to disk with `write_json()`, I get Latin characters as question marks (these were formatted correctly in the original file): 

```
{
    "text": "Mas mais ou atrav�s senhora ver essa oportunidade mais tarde te ligo novamente essa nossa linha de cr�dito eu t� com a encomenda leva um prazo de at� 15 dias corridos para o cimento l� resid�ncia. Ele est� bloqueado s� o senhor quem pode efetuar o desbloqueio enquanto voc� n�o deixou que � a senhora ser� cobrado em nada. D� pra entrar agora pra proximidade",
          "speaker": "2",
          "start": 115.22,
          "end": 132.64
        },
```

Is there any way I can format this correctly with `write_json()`? Or is it something I should do before writing to disk? Thanks for any help.

**Comment by psychelzh** [comment]
Fixed now. See #226 .
