### ISSUE TITLE
Issue while converting data in json file to a data frame [lexical error]

### ISSUE THREAD

**Issue by devarshi11github** [jeroen/jsonlite#213]
I am using 'tweetscores' package to extract tweets corresponding to a key word. I get the data in json format but when I am trying to convert it to a data frame I get the following error. This question has been raised in some threads but I could not get a proper solution. Also I believe that json has some issues handling 'backslashes' have that error as well. Is it possible to skip this error and continue without breaking the 'lapply'

Error: lexical error: invalid char in json text.
          296> <U+0361>Â° <U+4EBA>\"],"url":null,"entities":{"descript
                     (right here) ------^ 

I am using the following segment of code. 

__tweet_file <- "tweetlist.json"
con <- file(tweet_file,"r")
input <- readLines(con, -3L)
close(con)

tweetdatasmall <- ldply(lapply(input, function (x) t(unlist(fromJSON(x, flatten = TRUE)))))

**Comment by jeroen** [comment]
You need to share your `tweetlist,json` file for me to help you find the problem.

**Comment by devarshi11github** [comment]
Attached the zip file. Let me know if you need any other info

[tweetlist.zip](https://github.com/jeroen/jsonlite/files/1485692/tweetlist.zip)

**Comment by jeroen** [comment]
The file has corrupted character. How did you generate this file? Did you copy paste it from somewhere?

**Comment by devarshi11github** [comment]
I used the 'tweetscores' package to extract tweet. Used the function 'search tweet'. It generates the list in json format. [I have changed the path of the file in the below mentioned code]

searchTweets("text",n = 10000, filename ="tweetlist.json", oauth_folder = "~credentials",
             until = NULL, since_id = NULL, lang = "en", sleep = 1, verbose = TRUE)

**Comment by jeroen** [comment]
It looks like the tweetscores package writes text files to disk and then read them again, messing up the encoding (I guess you're on windows?). Try this

```r
json <- readLines("~/Downloads/tweetlist.json")
isvalid <- sapply(json, jsonlite::validate, USE.NAMES = FALSE)
tweets <- lapply(json[isvalid], jsonlite::fromJSON, simplifyVector = FALSE)
tweetdata <- tibble::as_tibble(jsonlite:::simplify(tweets, flatten = TRUE))

```

**Comment by devarshi11github** [comment]
Thanks for sharing the code. I will try with these and let you know. I feel that jsonlite function shows error with some special characters such as <U+0361> or <U+4EBA> (https://www.compart.com/en/unicode/U+0361). These are very common characters in twitter (as user name). 

Similarly issue with 'backlashes'. I remember I extracted about 40k tweets and while I was transforming (json file) into a data frame, there was a lexical error because of a 'backlash' (for a particular username). I just opened the json file in worddoc and replaced the backlash for that particular user (just 3 replacements) and the code worked perfectly fine.

**Comment by devarshi11github** [comment]
Hi Jereon,

Thanks a lot. The set of codes worked really well. It solves one of my big problem, where I want to use 'tweetscores' package for extracting tweets instead of the more common 'twitteR' package. One only minor issue, where the 'tweetdata' variable is not exactly a data frame since some of the columns are of list type. Hence the data frame is no longer 2-dimensional and can't be exported to a 2d csv file. A simple code such as the one below can be used to convert it to a data frame:
tweetdata.df <- data.frame(lapply(tweetdata,as.character), stringsAsFactors = FALSE)

and then using
write.csv(tweetdata,"tweetdata.csv")
 the csv file can be generated. Once again thanks for your support
