### ISSUE TITLE
toJSON "digits" argument not always respected

### ISSUE THREAD

**Issue by br00t999** [jeroen/jsonlite#214]
Hi,

Further to issue #12, I have noticed that the digits argument is not always respected by toJSON for small numbers. I tried playing with various options, tried `use_signif = TRUE` (per issue #184) but to no avail.

```
> library(jsonlite)
> toJSON(0.1, auto_unbox = TRUE, digits = 8)
0.1 
> toJSON(1e-1, auto_unbox = TRUE, digits = 8)
0.1 
> toJSON(1e-2, auto_unbox = TRUE, digits = 8)
0.01 
> toJSON(1e-3, auto_unbox = TRUE, digits = 8)
0.001 
> toJSON(1e-4, auto_unbox = TRUE, digits = 8)
0.0001 
> toJSON(1e-5, auto_unbox = TRUE, digits = 8)
1e-05 
> options(scipen = 500)
> toJSON(1e-5, auto_unbox = TRUE, digits = 8)
1e-05 
> toJSON(1e-5, auto_unbox = TRUE, digits = NA)
1e-05 
toJSON(1e-5, auto_unbox = TRUE, digits = 20, use_signif = TRUE)
1e-05 
```

```
> sessionInfo()
R version 3.4.2 (2017-09-28)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.3 LTS

Matrix products: default
BLAS: /usr/lib/libblas/libblas.so.3.6.0
LAPACK: /usr/lib/lapack/liblapack.so.3.6.0

locale:
 [1] LC_CTYPE=en_CA.UTF-8       LC_NUMERIC=C               LC_TIME=en_CA.UTF-8        LC_COLLATE=en_CA.UTF-8    
 [5] LC_MONETARY=en_CA.UTF-8    LC_MESSAGES=en_CA.UTF-8    LC_PAPER=en_CA.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_CA.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] jsonlite_1.5

loaded via a namespace (and not attached):
[1] compiler_3.4.2 tools_3.4.2    yaml_2.1.14 
```

Thanks!

**Comment by jeroen** [comment]
Which of these are incorrect?

**Comment by br00t999** [comment]
So sorry...

```
 toJSON(0.00001, auto_unbox = TRUE, digits = 6)
1e-05 
> toJSON(0.0000001, auto_unbox = TRUE, digits = 10)
1e-07 
```

I am working on the assumption that the output should be the same as the input in the snippet above...

**Comment by jeroen** [comment]
They are the same. It's just a different notation for the same number.

**Comment by br00t999** [comment]
Sorry if I am being dense, but shouldn't the output for

toJSON(0.0000001, auto_unbox = TRUE, digits = 10)

be 

0.0000001?

**Comment by jeroen** [comment]
No it shouldn't. There is no difference between `0.0000001` and `1e07`. Once you enter them in R they are exactly the same number. Why are you trying to prevent scientific notation? It's shorter and just as correct.

**Comment by br00t999** [comment]
The JSON I am generating is being consumed by a client that does not handle the scientific notation properly. I guess I can just coerce the input to a string, no biggie.

**Comment by jeroen** [comment]
Are you sure that's the problem? I can't think of any json client that won't read scientific notation. It's just standard formatting for doubles and has been part of the json standard since day 1.

**Comment by br00t999** [comment]
Long story. You are of course correct. I am just going to coerce to string and use the little function suggested in https://stackoverflow.com/questions/3443687/formatting-decimal-places-in-r to get the decimal places I want. Thanks for taking the time to reply, much appreciated!
