### ISSUE TITLE
Akbar

### ISSUE THREAD

**Issue by Gullakh** [jeroen/jsonlite#216]
I am getting the following error while loading the file to R
library(jsonlite)
> system.time(x <- fromJSON("Location History.json"))
Error: lexical error: invalid char in json text.
                                       Location History.json
                     (right here) ------^

Please help me in resolving the issue

**Comment by jeroen** [comment]
It means the file `"Location History.json"` does not exist and is also not literal jsonl

**Comment by Gullakh** [comment]
I have this LocationHistory.json on my MacBook which I'm unable to parse to R. Please let me know how to do it.

**Comment by Gullakh** [comment]
[1] FALSE

**Comment by Gullakh** [comment]
This file has been downloaded from takeout.google.com and was a zipped file. Unzipped and saved in a folder.
