### ISSUE TITLE
fromJSON(<file>) and read_json are very slow

### ISSUE THREAD

**Issue by wch** [jeroen/jsonlite#219]
Example (the first part just downloads data):

```R
# =============================================
# Part 1: download some crandb data
# =============================================
library(jsonlite)
library(magrittr)

skip_lines <- function(text, head = 1e6, tail = 1e6) {
	text <- strsplit(text, "\n")[[1]]
	tail <- min(tail, max(0, length(text) - head))
	skip_text <- if (length(text) > head + tail) {
		paste("\n... not showing", length(text) - head - tail, "lines ...\n")
	} else {
		character()
	}
    c(head(text, head), skip_text, tail(text, tail)) %>%
		paste(collapse = "\n")
}

DB <- function(api, head = 1e6, tail = head) {
  paste0("http://crandb.r-pkg.org", "/", api) %>%
    httr::GET() %>%
  	httr::content(as = "text", encoding = "UTF-8") %>%
  	jsonlite::prettify()
}

all_data_json <- DB("/-/all?limit=1000")
all_data_json <- prettify(all_data_json, indent = 2)
write_json(all_data_json, "all1000.json")

# =============================================
# Part 2: run tests
# =============================================

# readChar + fromJSON
system.time({
  all_data_json <- readChar("all1000.json", file.info("all1000.json")[["size"]], useBytes = TRUE)
  all_data_json <- fromJSON(all_data_json)
})
#   user  system elapsed 
#  0.304   0.029   0.336 


# fromJSON(<file>)
system.time({
  all_data_json <- fromJSON("all1000.json")
})
# ... I gave up after about a minute
```

`read_json` is just a wrapper for `fromJSON` that takes a file, so it has the same performance issues.

cc @hadley

**Comment by jeroen** [comment]
I think there is a bug in your example at the line

```r
write_json(all_data_json, "all1000.json")
```

The object `all_data_json` is already a json string and here you are converting it to json again so you're basically just escaping a really large string.

**Comment by jeroen** [comment]
ping @wch can you have a look if this solves your problem, or if there is another issue?

**Comment by wch** [comment]
You're right, I was saving it the wrong way. :(

I'm curious though: why does `fromJSON(readChar())` give a different result from `fromJSON("filename")` (nested list vs. 1-element char vector)?

**Comment by jeroen** [comment]
I don't understand your question. Where do they give different results?

**Comment by wch** [comment]
Now that I test it again, they're both giving the same result (a string). I must have been doing something weird when I was testing it earlier. Sorry about the confusion.

**Comment by sanjmeh** [comment]
The original question remains unanswered: 
why is `fromJSON()` (or `read_json()`) so slow?
_(It actually doesn't matter if we do a `readChar()` before doing a `fromJSON()`. The readChar() is almost instantaneous (200 msec for a 75MB json file) while fromJSON() takes around 15 seconds._
In python the same json file is read in super fast. There is no comparison of the speeds.
