### ISSUE TITLE
base64_enc add \n when using a long string

### ISSUE THREAD

**Issue by sipemu** [jeroen/jsonlite#220]
when using long input chars then a new line chars **\n** is added. See example below.

## Example Code

```
x <- charToRaw("username:veryveryverylonglonglonglonglonglonglonglongpassword")

enc1 <- base64enc::base64encode(x)
enc2 <- jsonlite::base64_enc(x)
````
## Results

**enc1 :**

dXNlcm5hbWU6dmVyeXZlcnl2ZXJ5bG9uZ2xvbmdsb25nbG9uZ2xvbmdsb25nbG9uZ2xvbmdwYXNzd29yZA==

**enc2:**

dXNlcm5hbWU6dmVyeXZlcnl2ZXJ5bG9uZ2xvbmdsb25nbG9uZ2xvbmdsb25nbG9uZ2xvbmdw\n YXNzd29yZA==

**Comment by jeroen** [comment]
Yes this is expected. Linebreaks are ignorable in base64. Some other packages (such as openssl) have a parameter to turn linebreaks on/off but the encoder in jsonlite is very basic.
