### ISSUE TITLE
Google trends power bi

### ISSUE THREAD

**Issue by jienkles** [jeroen/jsonlite#221]
Hi There 
Ive tried to load google trends package through R in power bi and receive this error.
Any help will be appreciated. thanks
dean

Details: "ADO.NET: R script error.
Creating a generic function for 'toJSON' from package 'jsonlite' in package 'googleVis'
Error: No connection object has been created. Use 'gconnect()' first.
Execution halted

**Comment by jeroen** [comment]
You need to report this in googlevis or your BI tool.
