### ISSUE TITLE
impossible to export some numbers as decimal (rather than expnential) notation

### ISSUE THREAD

**Issue by kburnham** [jeroen/jsonlite#224]
It appears to be impossible to force toJSON to use decimal notation in at least some cases:
```
jsonlite::toJSON(l, pretty = TRUE, digits = 9, auto_unbox = TRUE)
{
  "y": 2.262406575e-06
}
```
This behavior appears to be caused by the `num_to_char()` function:
``` jsonlite:::num_to_char(l$y)
[1] "2.26240657478789e-06"
```

However, the `num_to_char_R()` function exhibits the desired behavior:
```
jsonlite:::num_to_char_R(l$y)
[1] "0.00000226240657478789"
```

Can the toJSON function be modified to force it to never use exponential notation? The digits argument does not appear to do this.

**Comment by jeroen** [comment]
No you cannot force this. Scientific notation is the natural notation for doubles because it works for very large or very small numbers. Why do you want this?

**Comment by kburnham** [comment]
I am trying to match exactly a preexisting json export. But there are other ways to solve the problem.
