### ISSUE TITLE
The Json parsing error caused by BOM header.

### ISSUE THREAD

**Issue by tianmotianxiang** [jeroen/jsonlite#228]
{Rows:[{"SimNum":"64959409512","CarId":"999593","CarNum":"鄂A21N65"},{"SimNum":"64959426194","CarId":"1010852","CarNum":"鄂A3QD28"},{"SimNum":"64959433733","CarId":"999596","CarNum":"鄂A55LN8"}]}

`CarList <- jsonlite::fromJSON(CarList) # from jsom car list
Error: lexical error: invalid char in json text.
                                      {Rows:[{"SimNum":"64959409512","
                     (right here) ------^`

**Comment by jeroen** [comment]
This has nothing to do with BOM. You need to quote the `rows` key. All strings in json must be quoted.

**Comment by tianmotianxiang** [comment]
`{Rows:[{"SimNum":"64959409512","CarId":"999593","CarNum":"鄂A21N65"},{"SimNum":"64959426194","CarId":"1010852","CarNum":"鄂A3QD28"},{"SimNum":"64959433733","CarId":"999596","CarNum":"鄂A55LN8"}]}`

@jeroen ，**Based on the json data above, you can write a fromJSON code.**

**Comment by tianmotianxiang** [comment]
RJSONIO::fromJSON(CarList)
