### ISSUE TITLE
Error installing jsonlite. "Error in loadNamespace”

### ISSUE THREAD

**Issue by sumitsar** [jeroen/jsonlite#229]
I am trying to install jsonlite package for R and it's failing with this error:

**install.packages("jsonlite")**

_Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : there is no package called ‘jsonlite’ Calls: ... tryCatch -> tryCatchList -> tryCatchOne -> Execution halted_

For that matter, any package I try to install fails with this message. For an example, if I try to install devtools using **install.packages("devtools", repos = "https://cloud.r-project.org/")** it fails with the following:

_Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) :
  there is no package called ‘jsonlite’
Calls: <Anonymous> ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
Execution halted
The downloaded source packages are in
        ‘/tmp/RtmpbkyMoe/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
There were 12 warnings (use warnings() to see them)_

Any pointers will be appreciated.

**Comment by jeroen** [comment]
Make sure the packages isn't loaded while you try to reinstall it.

**Comment by jeroen** [comment]
Oh you're using microsoft R? Probably an issue with their repositories. Can you try:
```r
install.packages("jsonlite", repos = 'https://cran.r-project.org')
```

**Comment by sumitsar** [comment]
Yeah, seems to be like that. I tried your command and it failed with the same error. I'm not sure if jsonlite has any dependency on any other package?

**Comment by jeroen** [comment]
You cannot install a package while it is in use. You need to close all your R sessions, then start a clean R session and type `install.packages("jsonlite")`

**Comment by malkaihu** [comment]
Thanks.
After a few attempts, your suggestion worked.

Before that, starting a new R session and running
'devtools::install_github("jeroen/jsonlite")'
did not work.

Thanks for your help and your quick response.

**Comment by nonotionforsure** [comment]
where I can install  install.packages("jsonlite", repos = 'https://cran.r-project.org') ?
