### ISSUE TITLE
invalid char in json text using fromJSON()

### ISSUE THREAD

**Issue by malkaihu** [jeroen/jsonlite#230]
Hi,

I am using the fromJSON() function from my code, and it works only for some URLs on my work computer.
Some URLs, which work perfectly fine when pasted into a browser, do not work in fromJSON().

I should stress that on my personal laptop my program works perfectly. But on the work computer it does not work at all for certain URLs.

Here are the relevant parts of my code:
`#This works fine on my work computer:`
`temp <- fromJSON("https://api.gdc.cancer.gov/projects?facets=program.name&size=100&sort=primary_site:asc&prettify=true")`

`filesURL <- "https://api.gdc.cancer.gov/files?filters=%7B%22op%22%3A%22and%22%2C%22content%22%3A%5B%7B%22op%22%3A%22and%22%2C%22content%22%3A%5B%7B%22op%22%3A%22in%22%2C%22content%22%3A%7B%22field%22%3A%22cases.project.program.name%22%2C%22value%22%3A%22TCGA%22%7D%7D%2C%7B%22op%22%3A%22and%22%2C%22content%22%3A%5B%7B%22op%22%3A%22in%22%2C%22content%22%3A%7B%22field%22%3A%22cases.project.disease_type%22%2C%22value%22%3A%22%2ACarcinoma%22%7D%7D%2C%7B%22op%22%3A%22in%22%2C%22content%22%3A%7B%22field%22%3A%22cases.project.primary_site%22%2C%22value%22%3A%22Brain%22%7D%7D%5D%7D%5D%7D%2C%7B%22op%22%3A%22and%22%2C%22content%22%3A%5B%7B%22op%22%3A%22in%22%2C%22content%22%3A%7B%22field%22%3A%22type%22%2C%22value%22%3A%22copy_number_segment%22%7D%7D%2C%7B%22op%22%3A%22in%22%2C%22content%22%3A%7B%22field%22%3A%22data_category%22%2C%22value%22%3A%22Copy%20Number%20Variation%22%7D%7D%2C%7B%22op%22%3A%22in%22%2C%22content%22%3A%7B%22field%22%3A%22data_type%22%2C%22value%22%3A%22Masked%20Copy%20Number%20Segment%22%7D%7D%2C%7B%22op%22%3A%22in%22%2C%22content%22%3A%7B%22field%22%3A%22experimental_strategy%22%2C%22value%22%3A%22Genotyping%20Array%22%7D%7D%5D%7D%5D%7D&fields=file_id&size=5000&related_files=false"`
`#The following line throws the error`
`fileIDs <- fromJSON(filesURL)`

The exact wording of the error message are:
> Error: lexical error: invalid char in json text.
                                       https://api.gdc.cancer.gov/file
                     (right here) ------^

When I tried to debug it, I realised the problem was that in the "if-else" statement which checks if it's a connection and otherwise tries to parse it from a JSON format, it does not recognise it as a URL (something like 'con = false' if I remember correctly) and it therefore tries to parse the actual URL as though it were a JSON, which it obviously can't do.

I am wondering, could it have anything to do with the length of the URL? If so, why does it work on my personal computer? And what settings can I change on my work computer in order for it to work?

My PC runs Windows 8.1. At work I tried it on Windows 10 and Windows 7.
I disabled the anti-virus software and the firewall, but it still doesn't work.

I would appreciate help with this issue.

Thank you very much!

**Comment by jeroen** [comment]
Yes I think the URL is too long. Can you try this:

```r
fileIDs <- fromJSON(url(filesURL))`
```

**Comment by malkaihu** [comment]
Hi Jeroen,

Thanks for your response.

I have been away from work for several weeks so could not reply.

Now I am back, I have tried your suggestion but there is no improvement.
Is there anything else you can suggest?
It is really important to me to be able to get those file IDs.
As I wrote, it works fine on my computer, with even longer URLs, but on my
work computer it does not.

I would greatly appreciate help in sorting out this issue.

Thanks in advance,

Malkaihu

**Comment by jeroen** [comment]
Did you try the suggestion above to wrap the url in the `url()` function?

Also the problem should be fixed in the master branch:

```r
devtools::install_github("jeroen/jsonlite")
```

**Comment by malkaihu** [comment]
Yes, I have tried the fix you had suggested, but it still did not work.
The error message may have been slightly different.

When I debug, it seems to me that the problem is here:
By the time the highlighted part is executed, txt still contains the URL...
Could it be due to the limit you put on the number of bytes?
Perhaps you can change that?

Or with the validate function?

Under closer inspection, I see this:

For some reason, the "inherits(txt, "connection")" function returns false
(which, of course, cause the function to try to parse the URL as a JSON,
which is the problem).
Do you know why that might be?

Thanks in advance,

malkaihu

**Comment by malkaihu** [comment]
Yes, I have tried the fix you had suggested, but it still did not work.
The error message may have been slightly different.

I did not understand your second suggestion 

> Also the problem should be fixed in the master branch:
> devtools::install_github("jeroen/jsonlite")
Do you mean I should install that instead of the jsonlite package?

When I debug, it seems to me that the problem is in this part of the function:
![image](https://user-images.githubusercontent.com/33328607/39317116-7e27a86e-4983-11e8-90f2-9776e52baa9e.png)
By the time the highlighted part is executed, "txt" still contains the URL and not the JSON which the URL should have returned...
Could it be due to the limit you put on the number of bytes?
Perhaps you can change that?

Or with the validate function?

Under closer inspection, I see this:
![image](https://user-images.githubusercontent.com/33328607/39317166-9df4a7b4-4983-11e8-80f0-824f0c69d564.png)

For some reason, the "inherits(txt, "connection")" function returns false
(which, of course, cause the function to try to parse the URL as a JSON,
which is the problem).
Do you know why that might be?
What can I do about it?

Thanks in advance,

malkaihu

**Comment by jeroen** [comment]
> Do you mean I should install that instead of the jsonlite package?

Yes, this is the latest version that is not yet available on CRAN. If you install from there it will be fixed.

**Comment by malkaihu** [comment]
Great, I will try that right now.

Thanks!

**Comment by malkaihu** [comment]
Wow!!!

The program runs perfectly and downloads the files!!

Thank you so much for sorting it out!

(If you don't mind, I would love to know what you changed to get it to work.)

I appreciate you patience and your quick, professional, replies.

Thanks!

P.S. The issue in the above comment still applies. Any suggestions for that please? Thanks!

**Comment by jeroen** [comment]
The rtools warnings are a temporary issue while we upgrade from R 3.4 to R 3.5 released this week.

**Comment by malkaihu** [comment]
Cool, thanks!

Do we need to upgrade our versions of R manually?

**Comment by jrtechs** [comment]
I got the same error today. This occurred for me when I tried to open a file which did not exist. As a fix to that particular issue, a check for the file existence would be great just so we can give a different warning.

**Comment by malkaihu** [comment]
Thanks!

It worked with the updated version.
Thanks and sorry for the late reply.
