### ISSUE TITLE
jsonlite toJSON digits arg beyond 15 not honored

### ISSUE THREAD

**Issue by fangbinggmail** [jeroen/jsonlite#231]
jsonlite toJSON digits = 16 or greater not honored. example
library(jsonlite)
toJSON(pi, digits = 15)
print(pi, digits = 15)
toJSON(pi, digits = 16)
print(pi, digits = 16)
produces below output. The last digit is not showing as compared to print().
> library(jsonlite)
> toJSON(pi, digits = 15)
[3.14159265358979] 
> print(pi, digits = 15)
[1] 3.14159265358979
> toJSON(pi, digits = 16)
[3.14159265358979] 
> print(pi, digits = 16)
[1] 3.14159265358979**3**

> sessionInfo()
R version 3.4.4 (2018-03-15)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] jsonlite_1.5

loaded via a namespace (and not attached):
[1] compiler_3.4.4 tools_3.4.4

**Comment by jeroen** [comment]
This is the limit of double precision.

**Comment by fangbinggmail** [comment]
Didn't I read the max digits would be 22? Are you saying print(pi, digits=20) would have produced random stuff after 15 digits?

**Comment by fangbinggmail** [comment]
I was trying to do round trip from a json file that had more than 15 digits (17digits in my case). fromJSON did produce an R object that has 17 digits when doing print() on it. But toJASON() on it loses the digits after the 15th.

**Comment by jeroen** [comment]
Yes IIRC we can't guarantee correctness of digits after 16.

**Comment by jeroen** [comment]
Note that in R you can print more digits, but they are wrong. Try this:

```r
print(pi, digits = 22)
```
And now lookup the real value of `π`.

**Comment by fangbinggmail** [comment]
Aha, so this looks to be an R limitation then?
Is there a class like Decimal to represent arbitrary precision in R that could be plugged into jsonlite?

**Comment by fangbinggmail** [comment]
Thanks for your prompt response and explanations! I can close the issue then.

**Comment by fangbinggmail** [comment]
Does it make sense to have toJSON() to add 2 more digits, even though the last two digits are not reliable, to achieve the round-trip like below?
fromJSON(toJSON(pi, digits = 20)) ==pi

Then again, using == on floats makes no sense anyway. Guess I'll close the issue anyhow.
