### ISSUE TITLE
Called from: parse_con(txt, bigint_as_char)

### ISSUE THREAD

**Issue by MihalisPapatsimpas** [jeroen/jsonlite#232]
I have a shiny app with an actionButton,which when it is pressed some computations are done in the background and then a plot appears in the mainPanel. But when I press the actionButton and then immediately close the app window  I get this error: Called from: parse_con(txt, bigint_as_char)

I searched it in google and found reference in your respositiry. What is the meaning of this error and how could i solve it?

**Comment by jeroen** [comment]
I really have no idea, I think it has something to do with how shiny interrupts an R process.
