### ISSUE TITLE
prettify() ignores max.print option

### ISSUE THREAD

**Issue by bradleyjeck** [jeroen/jsonlite#233]
Thanks for this great package.

I'm using jsonlite in conjuction with rmarkdown to document a json api.  Some of the responses from the server are quite long and repetitive so I'd like to truncate them.   I haven't been able to get prettify() to respond to the max.print option.  

Is this expected?  Is there another way to truncate the output?

Thanks in advance.

**Comment by jeroen** [comment]
Yes it is expected. Prettify uses an internal function in yajl to prettify a json string. It does not call back to R at all. 

If you want to truncate the output for printing only I guess you can just use `substring()` in R. If you actually want to remove some of the json, you will have to parse it using `fromJSON()` and then remove the part you want, and then convert back with `toJSON()`.
