### ISSUE TITLE
Error :: Importing json file in R

### ISSUE THREAD

**Issue by Selvamjn** [jeroen/jsonlite#234]
I'm getting below error while importing json file in R

data <- fromJSON("C:/Users/selvamj/OneDrive/Analytics/MongoDB/MongoTicket.json")
Error in parse_con(txt, bigint_as_char) : 
  lexical error: invalid char in json text.
                        {      "_id" : NumberLong(8800389001178),     
                     (right here) ------^

**Comment by jeroen** [comment]
That's not a json file, it is "mongo extended json".

**Comment by Selvamjn** [comment]
I'm a beginner, I would appreciate if you can help me to proceed further. Do I have a way to convert this into json file? or how to import "mongo extended json" in R?

**Comment by jeroen** [comment]
You can't read this file in R because it is specific to mongodb.

The easiest way to get your data is in R is reading it directly from mongodb using the mongolite package: https://jeroen.github.io/mongolite/

**Comment by Selvamjn** [comment]
Sure, will try that, thanks a lot for your time!
