### ISSUE TITLE
unbox() Doesn't work with factors

### ISSUE THREAD

**Issue by MrFlick** [jeroen/jsonlite#235]
The `unbox()` function doesn't seem to work with factors. Is this by design? For example

    unbox(factor("A"))
    # Error: Only atomic vectors of length 1 or data frames with 1 row can be unboxed.
    unbox(as.character(factor("A")))
    # [x] "A"

That seems to happen because of the check at

    if (!is.vector(unclass(x)) || !is.atomic(x) || length(dim(x)) > 1) {
        stop("Only atomic vectors of length 1 or data frames with 1 row can be unboxed.")
    }

and in this case `is.vector()` returns false because the un-classed factors retain a "levels" attribute.

```
str(unclass(factor("A")))
#  atomic [1:1] 1
#  - attr(*, "levels")= chr "A"
```
A quick fix would be

    if (!(is.vector(unclass(x)) || is.factor(x)) || !is.atomic(x) || length(dim(x)) > 1) {
        stop("Only atomic vectors of length 1 or data frames with 1 row can be unboxed.")
    }

**Comment by jeroen** [comment]
That sounds reasonable, can you send a PR?

**Comment by ChrisMuir** [comment]
FYI, the example given `unbox(factor("A"))` does not throw an error in the current dev version (returns `"A"`). [This](https://github.com/jeroen/jsonlite/commit/8909c49725ef3e72156a6e3d0025c69b3ad224d8#diff-61d01d25214720ea051c80d78d910209) commit removed the issue with factor inputs.
