### ISSUE TITLE
support for ietf "json schema"

### ISSUE THREAD

**Issue by r2evans** [jeroen/jsonlite#237]
@jeroen, any interest in incorporating schema (validation) support such as http://json-schema.org/? I wouldn't necessarily expect it to be within `jsonlite` (it is likely non-trivial and not required for most), so perhaps a new package `jsonlite.schema`.

**Comment by jeroen** [comment]
Have you tried cran packages jsonvalidate and jsonld ?

**Comment by r2evans** [comment]
No, and I'll take a look.

On casual reading, it appears that they are different: while I imagine that it will indicate when JSON in syntactically invalid, it is intended to verify that the structure and types within it follow defined rules (schema).

For instance, taking the "geographic coordinate" example from http://json-schema.org/examples.html:

```json
{
    "id": "http://json-schema.org/geo",
    "$schema": "http://json-schema.org/draft-06/schema#",
    "description": "A geographical coordinate",
    "type": "object",
    "properties": {
        "latitude": { "type": "number" },
        "longitude": { "type": "number" }
    }
}
```

|json                                                          |additional options                  |valid |
|:-------------------------------------------------------------|:-----------------------------------|:-----|
|{"latitude":[30.3487],"longitude":[-87.306]}                  |                                    |TRUE  |
|{"latitude":[30.3487],"longitude":["-87.3059957"]}            |                                    |FALSE |
|{"latitude":[30.3487],"longitude":[-87.306],"elevation":[20]} |                                    |TRUE  |
|{"latitude":[30.3487],"longitude":[-87.306],"elevation":[20]} |"additionalProperties":false        |FALSE |
|{"latitude":[30.3487]}                                        |                                    |TRUE  |
|{"latitude":[30.3487]}                                        |"required":["latitude","longitude"] |FALSE |

I can see its use in API dev/testing as well as streaming validation.

---

My pre-issue searching was not very thorough, it appears. I just found [`validatejsonr`](https://cran.r-project.org/web/packages/validatejsonr/) built on RapidJSON, which [does appear to use this same JSON Schema draft](https://github.com/Tencent/rapidjson/blob/master/doc/schema.md).

So perhaps this issue was unnecessary. Thanks!

**Comment by jeroen** [comment]
I think both [jsonvalidate](https://cran.r-project.org/web/packages/jsonvalidate/) and [validatejsonr](https://cran.r-project.org/web/packages/validatejsonr/) allow for validating json schemas.
