### ISSUE TITLE
stream_in error: Error in (function (..., row.names = NULL, check.rows = FALSE, check.names = TRUE,  :    arguments imply differing number of rows: 37, 35

### ISSUE THREAD

**Issue by bux-derek** [jeroen/jsonlite#238]
Hi,

I'm using the stream_in functionality to load streaming JSON data from an API. This works great, though I'm running into problems when loading one particular request. The JSON objects have 37 variables. When loading the data i receive the error:

```
Imported 126688 records. Simplifying...
Error in (function (..., row.names = NULL, check.rows = FALSE, check.names = TRUE,  : 
  arguments imply differing number of rows: 37, 35
```
I tried running with a custom handler that simply stores the data in a variable, but also then I receive the error. 

Any idea how to overcome this issue?

Best,
Derek

**Comment by jeroen** [comment]
Can you include some example json data so we can reproduce this problem?

**Comment by bux-derek** [comment]
Hi Jeroen,

This took a while because the original data contains some sensitive data, so I had to find a way to extract it, and to anonymous it without loosing the original data structure. See attached.

[data_anonymous.json.zip](https://github.com/jeroen/jsonlite/files/2054152/data_anonymous.json.zip)

Looking forward to your response!

Best,
Derek

**Comment by jeroen** [comment]
Ah okay this is a different structure than we assume. Usually ndjson are lines of key-values e.g.:

```r
stream_out(iris)
# {"Sepal.Length":5.1,"Sepal.Width":3.5,"Petal.Length":1.4,"Petal.Width":0.2,"Species":"setosa"}
# {"Sepal.Length":4.9,"Sepal.Width":3,"Petal.Length":1.4,"Petal.Width":0.2,"Species":"setosa"}
# {"Sepal.Length":4.7,"Sepal.Width":3.2,"Petal.Length":1.3,"Petal.Width":0.2,"Species":"setosa"}
# {"Sepal.Length":4.6,"Sepal.Width":3.1,"Petal.Length":1.5,"Petal.Width":0.2,"Species":"setosa"}
# {"Sepal.Length":5,"Sepal.Width":3.6,"Petal.Length":1.4,"Petal.Width":0.2,"Species":"setosa"}
# ...
```

Your data is more like CSV, where the first row contains an array with labels, and other rows contain arrays with values. As a workaround you can read it like this:


```r
data <- jsonlite::stream_in(file("~/Downloads/data_anonymous.json"), simplifyDataFrame=FALSE)
```

That will gives you a list of arrays. You can manually try to turn that into a data frame. But be careful because some lines in your data have different lengths, so it is ambiguous which values are in those rows.

```r
unique(sapply(data, length))
#37 35 36

> which(sapply(data, length) < 37)
# [1]  43630  89682  95089 106703 109782 111386 111619 114606 114883 115396 116477 117934 # 120975 121049 125342 126344
```

**Comment by psychelzh** [comment]
@jeroen Run into this issue, too. But I think in this case a `list` of `data.frame`s should be returned. At least an argument can be used to opt in/out this behavior. Is it possible?

**Comment by jeroen** [comment]
@psychelzh that depends on your data structure, you can customize the process by specifying the `handler` function.

**Comment by psychelzh** [comment]
Thank you! Is there any example on this? The `handler` is a little hard to grasp its usage.

**Comment by jeroen** [comment]
There is an example in the `?stream_in` manual page

**Comment by psychelzh** [comment]
Thank you. But there is a line reads:

> When a custom handler function is specified, `stream_in` always returns `NULL`.

And then I do not know it is okay to use any handler if I just want import data.

**Comment by psychelzh** [comment]
The added content makes sense then! Thank you very much.
