### ISSUE TITLE
Compile fails on MacOS with both gcc and clang

### ISSUE THREAD

**Issue by adam-erickson** [jeroen/jsonlite#244]
Installation method (also errors on CRAN):

`devtools::install_github("jeroen/jsonlite")`

gcc error:

> base64.c:12:2: error: initializer-string for array of chars is too long [-fpermissive]
>   "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";

clang++ errors:

> base64.c:12:2: error: initializer-string for char array is too long
>         "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
> base64.c:37:8: error: assigning to 'unsigned char *' from incompatible type 'void *'
>         out = malloc(olen);
> base64.c:112:14: error: assigning to 'unsigned char *' from incompatible type 'void *'
>         pos = out = malloc(count);

Both compilers dislike `base64.c`.

**Comment by adam-erickson** [comment]
`/usr/local/bin/g++-8 -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG -Iyajl/api  -DU_STATIC_IMPLEMENTATION -Wall -mtune=core2 -g -O2 -I/opt/X11/include   -fPIC  -DU_STATIC_IMPLEMENTATION -Wall -mtune=core2 -g -O2 -I/opt/X11/include  -c base64.c -o base64.o`

**Comment by jeroen** [comment]
I can't reproduce that error, neither on my mac (with clang) nor with gcc-8 on Debian or Windows. I think you have a local config bug, maybe your gcc and clean headers are getting mixed up?

**Comment by adam-erickson** [comment]
It's the MS version of R, but that should not matter...

**Comment by adam-erickson** [comment]
Fixed. I changed the compiler to `gcc-8` instead of `g++-8` and it compiled correctly. The issue was that C++ is much more strict about type casting.

**Comment by Tejv1708** [comment]
Line 27: Char 28: error: assigning to 'int' from incompatible type 'void'
 list->value = v.pop_back() ; 
can anyone tell me what is wrong init ??

**Comment by jeroen** [comment]
@Tejv1708 please tell us your OS and compiler and show the full error output

**Comment by Tejv1708** [comment]
void depthCount(TreeNode *&root , int &depth ){
    if(root == NULL){
    return ;
    } 
    depthCount(root->left , depth+1) ;
        depthCount(root->right , depth+1) ;   
    }
    
    int minDepth(TreeNode* root) {
        int depth = 0;
     depthCount(root ,  depth );
        return depth ;
    }
Line 18: Char 29: error: non-const lvalue reference to type 'int' cannot bind to a temporary of type 'int' depthCount(root->left , depth+1) 
why this error comes ..?

**Comment by Tejv1708** [comment]
Less interaction with the server means now user can validat the input before sending the page to the server which causes less traffic observer which means less load on a server.

What is meaning of this line can anyone tell me ..?

**Comment by Tejv1708** [comment]
Increase interactivity means by using JS we can create an eye catching interfaces which can create to the user activities when user click over them scrolling the web page or the application.

What is meaning of this line can anyone tell me ..?
