### ISSUE TITLE
 No method asJSON S3 class: lm

### ISSUE THREAD

**Issue by pankaj-cliq** [jeroen/jsonlite#248]
Getting following error when saving glm model as JSON file.

Error: No method asJSON S3 class: lm

Code snippet:
# Build the model
model <- glm(Order~.-ID,dataset, family = "binomial")
model_step <- step(model)
jsoncars <- toJSON(model_step)

**Comment by SymbolixAU** [comment]
@pankaj-cliq use 

```r
toJSON(model_step, force = TRUE)
```

**Comment by IndrajeetPatil** [comment]
Can reproduce and using `force = TRUE` solves the issue, but it just removes the call:

``` r
library(statsExpressions)
library(jsonlite)

df <- one_sample_test(mtcars, wt, test.value = 3)

df$expression[[1]]
#> paste(italic("t")["Student"], "(", "31", ") = ", "1.26", ", ", 
#>     italic("p"), " = ", "0.218", ", ", widehat(italic("g"))["Hedges"], 
#>     " = ", "0.22", ", CI"["95%"], " [", "-0.13", ", ", "0.57", 
#>     "]", ", ", italic("n")["obs"], " = ", "32")

toJSON(df, pretty = TRUE)
#> Error: No method asJSON S3 class: call

toJSON(df, pretty = TRUE, force = TRUE)
#> [
#>   {
#>     "mu": 3,
#>     "statistic": 1.256,
#>     "df.error": 31,
#>     "p.value": 0.2185,
#>     "method": "One Sample t-test",
#>     "estimate": 0.2166,
#>     "conf.level": 0.95,
#>     "conf.low": -0.1294,
#>     "conf.high": 0.5661,
#>     "effectsize": "Hedges' g",
#>     "expression": {}
#>   }
#> ]
```

<sup>Created on 2021-02-27 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by jeroen** [comment]
There is no native json representation of a linear model. You have to extract the data from the model that you are interested in serializing to json, for example coef(lm) or summary(lm).
