### ISSUE TITLE
Escaping of forward slashes

### ISSUE THREAD

**Issue by hbchri** [jeroen/jsonlite#255]
jsonlite only escapes / to \/ if the forward slash is preceded by <, at least as far as I can read [escape_chars.c](https://github.com/jeroen/jsonlite/blob/master/src/escape_chars.c) 

I understand this is because escaping forward slashes in urls broke a bunch of packages. 

However, according to the json format as described on [json.org ](https://json.org) requires that forward slashes be escaped, and some parsers (PHP, apparently) will fail unless specifically instructed to accept unescaped forward slashes. 

![](http://www.json.org/string.gif)

Would it be possible to make escaping of forward slashes optional based on passing a parameter to toJSON?

**Comment by jeroen** [comment]
As far as I can remember, escaping the solidus is optional. 

The figure above indicates how the `\/` should be *parsed*, but it also says __Any UNICODE character except `"` or `\` or control character__. Hence it does not mandate that the solidus be escaped.

You can further validate that the unescaped solidus is fine on e.g. https://jsonlint.com/. In other words, this is a bug in PHP, or whatever parser fails to parse strings with `/`.
