### ISSUE TITLE
Add with_json() functions

### ISSUE THREAD

**Issue by richierocks** [jeroen/jsonlite#257]
It seems like a reasonably common code pattern is to get some JSON data, process it in R, then convert it back to JSON.

That makes me think that it could be useful to have functionality along the lines of the `withr` package.

A rough implementation could be something like

```r
#' @param txt A JSON string, URL or file. See \code{\link{fromJSON}}.
#' @param expr Some R code to process the converted object.
#' @param object_name A string naming the object to process.
#' @param ... Further arguments passed to \code{\link{fromJSON}}.
with_json <- function(txt, expr, object_name = deparse(substitute(txt)), ...) {
  assign(object_name, fromJSON(txt, ...))
  toJSON(eval(substitute(expr)))
}
```

Example usage is

```r
library(jsonlite)
jsoncars <- toJSON(mtcars, pretty=TRUE)
with_json(jsoncars, jsoncars$mpg + 1)
## [22,22,23.8,22.4,19.7,19.1,15.3,25.4,23.8,20.2,18.8,17.4,18.3,16.2,11.4,11.4,15.7,33.4,31.4,34.9,22.5,16.5,16.2,14.3,20.2,28.3,27,31.4,16.8,20.7,16,22.4]
```

Here's the same thing, setting the object name.

```r
with_json(jsoncars, x$mpg + 1, "x")
```

Likewise, you could use the `read_json()` and `write_json()` functions to do the same thing with JSON in a file.

```r
with_json_file <- function(path, expr, object_name = deparse(substitute(path)), ...) {
  assign(object_name, read_json(path, ...))
  write_json(path, eval(substitute(expr)))
}
```

**Comment by jeroen** [comment]
This sounds cool but it's beyond the scope of jsonlite. I try to keep things simple :) There is no need for this in jsonlite, it can easily be another pkg.
