### ISSUE TITLE
read_json should accept strings as input 

### ISSUE THREAD

**Issue by philip-khor** [jeroen/jsonlite#259]
Bug #161 introduces `read_json` to be more in line with `readr` and other packages. `readr` and `readxl` functions accept both file paths and strings as arguments, whereas `read_json` only accepts file locations. I understand this functionality is available in `fromJSON`, but it would be nice to have this functionality in `read_json` too. Thanks!

**Comment by jeroen** [comment]
We now have `parse_json()` to read strings. We specifically want to distinguish between file inputs and literal input in `read_json()` and `parse_json()`. If you want something that works with either, just use `fromJSON()`.
