### ISSUE TITLE
auto_unbox for nested tibbles not working

### ISSUE THREAD

**Issue by HanjoStudy** [jeroen/jsonlite#263]
Hi, 

Recently been working on an api where I prefer to have most of the fields unboxed. I structure my data using `tibbles` as to allow for a nice nested structure for the `json` output. I tried to use `auto_unbox = T`, but without any success. I had to unbox each list individually. An example of the problem (and solution) can be found here:

https://stackoverflow.com/questions/52891917/jsonlitetojson-too-many-brackets-in-r-unbox-json/52895966#52895966

Is this an `auto_unbox` feature or bug?

**Comment by jeroen** [comment]
A tibble is a data frame and therefore each element must be a vector. You should wrap your elements into a list instead of a tibble if you do not want this.
