### ISSUE TITLE
lexical error: invalid char in json text

### ISSUE THREAD

**Issue by cwtomas** [jeroen/jsonlite#266]
Error in parse_con(txt, bigint_as_char) : 
  lexical error: invalid char in json text.
                                   /**/jQuery21108336474839681438_1543
                     (right here) ------^

This is the error message, and I tried all the proposed solutions that I found online (including on github), it's still not working......the file that I was trying to parse is attached. Thank you.
[search[18].zip](https://github.com/jeroen/jsonlite/files/2627257/search.18.zip)

**Comment by jeroen** [comment]
The file you're trying to parse is not json but jsonp.

**Comment by cwtomas** [comment]
Yup, it’s already solved, thank you Jeroen.
