### ISSUE TITLE
Not correct form of json created by toJSON

### ISSUE THREAD

**Issue by liao02x** [jeroen/jsonlite#267]
The required JSON should be like this:
```
{"title":"This is a title", "body":"This is a body"}
```
But jsonlite::toJSON produces somthing like this:
```
{"title":["This is a title"], "body":["This is a body"]}
```
This causes error 402 when posting to github, please check it.

**Comment by jeroen** [comment]
Try setting auto_unbox = TRUE

**Comment by liao02x** [comment]
I figured it out after a while, so maybe you can make auto_unbox be true defaultly?

**Comment by jeroen** [comment]
No

**Comment by liao02x** [comment]
Why? Is it used anywhere? It is not a regular JSON format, is it?

**Comment by liao02x** [comment]
I did. It seems right. And github kept responding 402 without any useful information. Then finally I found where the problem is. Maybe you should add something to the documentation, emphasize the one-length-arry thing.
