### ISSUE TITLE
toJSON results in Error in vapply, for a structure as a column in a data frame

### ISSUE THREAD

**Issue by git-hub-user** [jeroen/jsonlite#270]
I have been using jsonlite for quite a while to serialize a complex R data structure that is generated by a package that is written by a partner of ours.
In a new version, I started to get an error during the serialization:

> Error in vapply(x, asJSON, character(nrow(x)), collapse = FALSE, complex = complex,  : 
>   values must be length 2,
>  but FUN(X[[1]]) result is length 1

I have been able to pinpoint this to the following: some field was modified to contain a structure as a column in a data frame. Here is a stripped-down data frame that reproduced the error:
`x <- structure(c(1, 2), .Dim = 2L)`
`xf <- data.frame(x)`
`jsonlite::toJSON(xf)`

My knowledge of R is insufficient to tell if this object makes any sense at all, so I will discuss this with a package supplier. However, until now, jsonlite has provided me with a fail-safe method to (de)serialize objects and to communicate the content with other systems, so I thought that, maybe, it is useful if jsonlite could cope with this structure as well, or report it as an unsupported structure.

Some of the session info:

- R version 3.5.1 (2018-07-02)
- Platform: i386-w64-mingw32/i386 (32-bit)
- jsonlite_1.6

**Comment by SymbolixAU** [comment]
That's an interesting structure, I would be keen to know what you expect the JSON equivalent to be?

As an interim solution you can use one of the other packages

```r
rjson::toJSON( xf )
# "{\"x\":[1,2]}"

RJSONIO::toJSON( xf )
# "{\"x\":[1, 2]}"

jsonify::to_json( xf )
# [{"x":1.0},{"x":2.0}]
```

**Comment by bmordue** [comment]
The example provided can be serialized with by setting `dataframe = "columns"`:`
``` R
jsonlite::toJSON(xf, dataframe = "columns")
# {"x":[1,2]} 
```

**Comment by SymbolixAU** [comment]
Or if you want to keep the 'row' behaviour you need to "correct" the structure of the column

```r
xf$x <- as.numeric( xf$x )
jsonlite::toJSON( xf )
# [{"x":1},{"x":2}]

```

**Comment by jeroen** [comment]
I don't understand, it doesn't error for me? 

```r
library(jsonlite)
x <- structure(c(1, 2), .Dim = 2L)
xf <- data.frame(x)
jsonlite::toJSON(xf)
## [{"x":1},{"x":2}]
```

Is this still an issue?

**Comment by git-hub-user** [comment]
> Perhaps there was a bug in R? If there is still a problem, please open a new issue.

I tested and also for me, this does _not_ cause an error in R 3.6.2.

I reinstalled R 3.5.1 and the error was thrown again. So, the issue was related to the version of R. 

In R 3.5.1 I also noticed the warning "package ‘jsonlite’ was built under R version 3.5.3". Therefore, I also installed R 3.5.3 and the error did not occur. _I can't say as wasn't warned..._

**Comment by git-hub-user** [comment]
For the other responses, thanks for your input.
I must admit I submitted the issue, but also discussed it with the package supplier and they rearranged the data structure, so the issue was solved for me that way and, frankly, I forgot about it.
