### ISSUE TITLE
toJSON for conditions (warning, error, message) and calls

### ISSUE THREAD

**Issue by s-fleck** [jeroen/jsonlite#276]
Could we get serialization of condition objects in R?  I'm not sure how this fits in the concept of JSONlite as the process would be rather lossy.

In principle It should be simple. Normal conditions are just lists with a `$message` and `$call` element. There will likely be no easy way to serialize calls, but they could at least be converted to character vectors. 
```
e <- tryCatch(stop("blubb"), error = function(e) e)
w <- tryCatch(warning("blubb"), warning = function(e) e)
m <- tryCatch(message("blubb"), message = function(e) e)
str(e)

# try-errors are bit more tricky, they are a character vector with an error condtion as attribute
te <- try(stop("try-error"))
str(te)
```

If there is interest in this, I could draft a pull request.

**Comment by jeroen** [comment]
I don't think this is in the scope of jsonlite. This package implements a mapping between standard R data types and json structures.

If you want to somehow coerce custom classes into json, either use `jsonlite::serializeJSON`, or write a wrapper function to converts your custom types into a standard R types and then feed to `toJSON`.

**Comment by s-fleck** [comment]
Ok thanks anyways. Conditions (such as warnings and errors) are pretty ubiquitous base R-objects and IMHO not more "custom classes" than data.frames are. What about making `toJSON()` a generic so users could write their own methods?

**Comment by jeroen** [comment]
> Conditions (such as warnings and errors) are pretty ubiquitous base R-objects 

Indeed, jsonlite is focused _data interchange_ and therefore only supports core _data_ types. The goal is to quickly and reliably serialize _data_ from R to the equivalent json representation and vice versa. 

I really like to avoid dragging in more complexity into this package to start supporting internal R types do not have a natural json representation.
