### ISSUE TITLE
Error in parse_con(txt, bigint_as_char) :    lexical error: invalid bytes in UTF8 string.

### ISSUE THREAD

**Issue by legopin** [jeroen/jsonlite#279]
## Issue Description
When attempting to use `fromJSON()` to download a JSON file from remote url, encounters a parsing error. According to other issues jsonlite by default uses UTF-8 encoding to process JSON files. 

Is there anything I'm missing?

Link to file: http://lookup-service-prod.mlb.com/json/named.player_info.bam?sport_code=%27mlb%27&player_id=650671

## Error Output
```
Error in parse_con(txt, bigint_as_char) : 
  lexical error: invalid bytes in UTF8 string.
          isplay_first_last_html":"Jos� Quijada","gender":"M","height_
                     (right here) ------^
```

## Reproducible Example

```R
library('jsonlite')
res = fromJSON('http://lookup-service-prod.mlb.com/json/named.player_info.bam?sport_code=%27mlb%27&player_id=650671')
```

**Comment by legopin** [comment]
Current workaround, this does not produce error

```R
library(RCurl)
library(jsonlite)
raw_data <- getURL("http://lookup-service-prod.mlb.com/json/named.player_info.bam?sport_code=%27mlb%27&player_id=650671")
res = fromJSON(raw_data)
res$player_info$queryResults$row$name_display_first_last
```

**Comment by jeroen** [comment]
Yes jsonlite assumes data is UTF-8 encoded as is required by the official json specification. However this server is sending latin1 encoded text.

**Comment by legopin** [comment]
Ah I see, oops I missed that, was assuming it was UTF-8 because it was JSON, didn't know servers could do this. Thanks for the help
