### ISSUE TITLE
Filter fromjson 

### ISSUE THREAD

**Issue by orlandoandradeb** [jeroen/jsonlite#280]
Hello 
I have been using  the function "fromjson" to get some dataframe from a server.   However, one of the problems is that manytimes the dataframe  is bigger of what I want so I started to make filters. 

But, is there a way to make filters in the request to the dataframe ? 

thank you.

**Comment by jeroen** [comment]
If the input is in ndjson format, you can use `jsonlite::stream_in()` to stream parse.

If it's really one big json blob try using `jq` (either the command line or jqr package) to filter.
