### ISSUE TITLE
Issue with fromJSON(Parsing a json record a field value "Infinity")

### ISSUE THREAD

**Issue by tysamuel** [jeroen/jsonlite#281]
> testDF<-stream_in(rawConnection(test))
 Found 1819000 records...
Error: lexical error: invalid char in json text.
          changeinvalue":0.0,"lessee1":+Infinity,"lesseesqft1":14244.0
                              (right here) ------^

**Comment by jeroen** [comment]
`Infinity` is not a valid json primitive, please check [rfc8259](https://tools.ietf.org/html/rfc8259):

> 6.  Numbers
> ....
> Numeric values that cannot be represented in the grammar below (such
>   as Infinity and NaN) are not permitted.
