### ISSUE TITLE
Choice of default number of digits = 4 in toJSON?

### ISSUE THREAD

**Issue by fennells** [jeroen/jsonlite#283]
Is there a particular reason the default number of digits for toJSON is set to 4 by default?

It would seem to me that you would want to always take as many digits as are available and only cut things back if the user specifically requests it, i.e. the default for digits in toJSON should be NA.

**Comment by jeroen** [comment]
We've had a million discussions about this already. Number formatting is very slow, adding 20 digits to every number adds a lot of performance overhead and also blows up the json output. This is often undesired. The default is a balance between performance and precision, not going to change.
