### ISSUE TITLE
Options for decimal precision 

### ISSUE THREAD

**Issue by byapparov** [jeroen/jsonlite#284]
This is in relation to r-dbi/bigrquery#320

It would be nice to have an options to set number of digits instead of passing value into toJSON function, e.g.:

```r
.onLoad <- function(libname, pkgname) {
  # Default options --------------------------------------------------------
  op <- options()
  defaults <- list(
    jsonlite.digits = 4
  )
  toset <- !(names(defaults) %in% names(op))
  if (any(toset)) options(defaults[toset])
  invisible()
}
```

This would reduce number of tickets raised with regards to rounding.

Alternatively you can recommend dependant packages to manage digits with own options to avoid clashes.

**Comment by jeroen** [comment]
This should be done in the dependant package, for example where `bigrquery` invokes `toJSON`. We can't make this a global option, because there are often many packages in an R session at the same time that all use jsonlite, and they may have different preferences.
