### ISSUE TITLE
Can't parse json Error: lexical error: invalid (non-hex) character occurs after '\u' inside string.

### ISSUE THREAD

**Issue by jj585** [jeroen/jsonlite#286]
When trying to parse json with fromJSON function I receive an error.

Error: lexical error: invalid (non-hex) character occurs after '\u' inside string.
          SrTm|@di@gBn[{q@|`BgXlxAcOf\uFjDkMiEcUiQgIi@E`WyC~YOp`@eZp^i
                     (right here) ------^

[error_ex.zip](https://github.com/jeroen/jsonlite/files/3425267/error_ex.zip)

**Comment by jeroen** [comment]
You have this sequence in your text which is not valid: `\uFjDk` (note this appears as `\\uFjDk` when you print the string in R.

I think you want to escape the backslash when you like so `\\\\uFjDk`. I'm guessing you copy pasted this text?

**Comment by jj585** [comment]
The json textstring that is in the "error_ex.R" file in json_str object was copied from the R console (response to http request against OSRM server).

It seems to work when I substitute \\\\ with \\ 

fromJSON(gsub("\\\\","\\", getURLAsynchronous(url))

**Comment by jeroen** [comment]
You shouldn't copy paste code that way. You need to read/write it programmatically otherwise strings do not get escaped properly.

**Comment by jj585** [comment]
I do not copy. Function getURLAsynchronous(url) returns json string which fromJSON could not parse.

Does not Work:
fromJSON(getURLAsynchronous(url))

Works:
fromJSON(gsub("\\","\", getURLAsynchronous(url))

**Comment by jeroen** [comment]
If you want me to look at this you need to provide a [reproducible example](https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example) of how you obtained this json data. Somewhere the escaping of the backslash got messed up, either at your source or at your end. There is no bug in jsonlite, your json is simply invalid.

You can use `jsonlite::validate()` to check if a string contains proper json or not.
