### ISSUE TITLE
lexical error: invalid char in json text

### ISSUE THREAD

**Issue by trakru** [jeroen/jsonlite#288]
i checked the other threads on this topic, but none of the errors are in a similar condition

Basically, i am using the API lookup for db-ip.com to create a JSON list of addresses and locations from IP address. Ddue to the nature of how the batch API is written, i am focred to create a URL as following:

`url <- paste0("http://API_url/","my_API_key/",[list_of_IP_addresses_separated_by_comma]`

`json_file <- fromJSON(url)
`

as long as my list is <100 values, the formula works just fine. However, if the list is bigger than that i get the following error

> Error: lexical error: invalid char in json text.
                                       http://api.db-ip.com/v2/aa24a1d
                     (right here) ------^

Is this a memory utilization error? should i try to create loops so i can go through my URL list in batches of 100 (i have over 100,000 list of addresses to map)

**Comment by jeroen** [comment]
URLs have a maximum length of 2048 characters.

**Comment by trakru** [comment]
yep - that explains it. i did resolve the issue by a workaround already though! 
Thank you for writing an excellent package
