### ISSUE TITLE
jsonlite  - Error: lexical error: invalid char in json text

### ISSUE THREAD

**Issue by Gomesdrg** [jeroen/jsonlite#290]
Hi, I have a large number of JSON files I am iterating through with jsonlite.

A subset is giving me the lexical error message above.  

However when I put a few of the files through a JSON validator (https://jsonlint.com/) it indicated the files as valid JSON files.

Should i be specifying an alternative character set vs UTF-8?  I noted you have commented to others previously that it should not be necessary.

If helpful I can send a sample JSON file directly but would not be able to post it on github.

Look forward to your feedback.

**Comment by alevashov** [comment]
I have similar issue, my string that I am trying to parse is below
`"{\"schema\":\"iglu:com.snowplowanalytics.snowplow/unstruct_event/jsonschema/1-0-0\",\"data\":{\"schema\":\"iglu:com.snowplowanalytics.snowplow/link_click/jsonschema/1-0-1\",\"data\":{\"targetUrl\":\"https://support.google.com/adwords/answer/1722066\032\033\017Y[‹PUH‹\b™[\031[Y[\u009d\022Y\bŽˆˆ‹\b™[\031[Y[\u009d\020Û\030\\ÜÙ\\ÈŽ–×K\b™[\031[Y[\u009d\025\030\\™Ù]\bŽˆ—Ø›\030[šÈŸ__"`

**Comment by jeroen** [comment]
Can you confirm your data passes on https://jsonlint.com/?

**Comment by alevashov** [comment]
> Can you confirm your data passes on https://jsonlint.com/?

not really see 

> Error: Parse error on line 1:
> {	\	"schema\":\"iglu:
> --^
> Expecting 'STRING', '}', got 'undefined'

Internal validation shows (t1 contains the string in question):
```
validate(t1)
[1] FALSE
attr(,"offset")
[1] 233
attr(,"err")
[1] "lexical error: invalid character inside string.\n          gle.com/adwords/answer/1722066\032\033\017Y[â€¹PUHâ€¹\bâ„¢[\031[Y[Â\u009d\022Y\bÅ½\n                     (right here) ------^\n"
> 
```

**Comment by jeroen** [comment]
You need to use the `cat(string)` output to paste on jsonlint.

**Comment by alevashov** [comment]
If in insert cat output, I am getting a different error:

```
Error: Parse error on line 6:
...: {			"targetUrl": "https://support.goo
----------------------^
Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[', got 'undefined'
```

**Comment by alevashov** [comment]
For the full context, I am decoding from base 64.

So it looks like:

```
m64 <- "eyJzY2hlbWEiOiJpZ2x1OmNvbS5zbm93cGxvd2FuYWx5dGljcy5zbm93cGxvdy91bnN0cnVjdF9ldmVudC9qc29uc2NoZW1hLzEtMC0wIiwiZGF0YSI6eyJzY2hlbWEiOiJpZ2x1OmNvbS5zbm93cGxvd2FuYWx5dGljcy5zbm93cGxvdy9saW5rX2NsaWNrL2pzb25zY2hlbWEvMS0wLTEiLCJkYXRhIjp7InRhcmdldFVybCI6Imh0dHBzOi8vc3VwcG9ydC5nb29nbGUuY29tL2Fkd29yZHMvYW5zd2VyLzE3MjIwNjY_aGw9ZW4tQVUiLCJlbGVtZW50SWQiOiIiLCJlbGVtZW50Q2xhc3NlcyI6W10sImVsZW1lbnRUYXJnZXQiOiJfYmxhbmsifX19"
m <- m64 %>% base64enc::base64decode() %>% rawToChar()
fromJSON(m)
```

and the last call returns an error I referred

**Comment by jeroen** [comment]
I don't know where you got that data but it looks corrupt. It contains a lot of gibberish. There is not much I can do to help you.
