### ISSUE TITLE
Vectorise fromJSON, parse_json and read_json

### ISSUE THREAD

**Issue by mgirlich** [jeroen/jsonlite#291]
Often, I need to parse a whole character vector and `parse_json()` then gives me a cryptic error message

``` r
jsonlite::parse_json(c('"a"', '"b"'))
#> Error: parse error: trailing garbage
#>                                  "a" "b"
#>                      (right here) ------^
```

One can now either use something like `lapply()` or (which is often faster!) collapse the input to a json array. Otherwise, there should be an error message.

Funnily enough, one can use a vector of length > 1 if concatenating it yields valid json, e.g.

``` r
jsonlite::fromJSON(c('["a"', ', "b"]'))
#> [1] "a" "b"
```

<sup>Created on 2019-09-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by artemklevtsov** [comment]
Simply use the following trick:

```r
fromJSON(paste0("[", lst, "]", collapse = ","))
```

**Comment by jeroen** [comment]
The input lines are concatenated because often they are part of a single json document like so:

```r
json <- readLines("https://api.github.com/users/jeroen")
jsonlite::parse_json(json)
```

So indeed, you need to use `lapply` if each line is a separate json document in your case.
