### ISSUE TITLE
curl is a Depends/Imports not a Suggests package

### ISSUE THREAD

**Issue by steveped** [jeroen/jsonlite#296]
Hi,

Whilst I realise that  `loadpkg("curl")` in `fromJSON()` should spit an error if the package `curl` is not installed, this doesn't seem to work when being called as a function by other packages, such as https://github.com/BioinformaticsFMRP/TCGAbiolinks. I've spent 4 hours trying to find the problem from their function `getGDCProjects()`, and it turned to be in their call to `fromJSON()`. I didn't have the package `curl` installed and no error message as you have specified was generated from their call. They did have the call wrapped in `tryCatch()` though. 

Their `getURL()` function (https://github.com/BioinformaticsFMRP/TCGAbiolinks/blob/master/R/internal.R#L760) was the culprit, and it's called from https://github.com/BioinformaticsFMRP/TCGAbiolinks/blob/master/R/query.R#L171

The package `curl` looks very much like a dependency for the function `fromJSON()` & should be listed in your `@Imports` section on that function, and also should be placed in your `Depends` or `Imports` section of your `DESCRIPTION` file, as is the current paradigm for roxygen based packages. This will help ensure any packages which depend on jsonlite will install correctly. I honestly can't think of any good reasons why this would be a bad idea, except for maybe... Windows?

Thanks in advance

**Comment by jeroen** [comment]
It works just fine:

```
> remove.packages('curl')
Removing package from ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library’
(as ‘lib’ is unspecified)
> jsonlite:::loadpkg('curl')
Error: Required package curl not found. Please run: install.packages('curl')
```

I can't fix it if some other package muffles this error. 

jsonlite will always be a zero-dependency package.

**Comment by steveped** [comment]
OK. I'll suggest they check their error handling. Thanks
