### ISSUE TITLE
Can all JSON structures be flattened?

### ISSUE THREAD

**Issue by bennlich** [jeroen/jsonlite#297]
I realize this is probably covered in the paper, but it might be helpful to add to an FAQ in the repo.

I'm wondering, am I guaranteed to be able to turn an arbitrary JSON result into a flattened data frame? Or do I need to worry about the structure of the JSON data I am working with? Are there any common caveats?

**Comment by jeroen** [comment]
No, you can't flatten tree structures into tables of course. The only thing we can flatten is nested data frames. Compare these:

```r
url <- 'https://api.github.com/users/jeroen/repos'

# Without flattening
df1 <- jsonlite::fromJSON(url)
colnames(df1)
colnames(df1$owner)

# With flattening
df2 <- jsonlite::fromJSON(url, flatten = TRUE)
colnames(df2)
```
