### ISSUE TITLE
Support reading Javascript notation for special floating point values

### ISSUE THREAD

**Issue by rok-cesnovar** [jeroen/jsonlite#302]
Hi, 

I am wondering if there is a possibility to extend `fromJSON()` to support other notations for special floating point values like Inf and Nan?

Currently you only support special values if they are encoded as strings.
```R
jsonlite::fromJSON('[1, "Inf", "-Inf", "NaN"]')
```

What I am wondering is if you would be willing to also support 
```R
jsonlite::fromJSON('[1, Infinity, -Infinity, NaN]')
```

I am primarily interested in being able to read these values in, not outputting them. The use case for this is that currently we need to produce different JSON files depending if the end use of the JSON is in R (with jsonlite) or in Python (with json package). 

This change would enable reading the same JSON in both Python and R. If you would be willing to consider this I am happy to work on a pull request.

**Comment by jeroen** [comment]
The json c parser library that we use only supports json. That is not json.
