### ISSUE TITLE
Error: 'parse_json' is not an exported object from 'namespace:jsonlite'

### ISSUE THREAD

**Issue by kswann-imb** [jeroen/jsonlite#309]
When I try to use `parse_json` to read a string formatted json I get the following error:

`Error: 'parse_json' is not an exported object from 'namespace:jsonlite'`

Package: jsonlite
Source: CRAN
Version: 1.6

Anonymized code:

```
result <- function(json_string) {
  df <- jsonlite::parse_json(json_string, simplifyVector = TRUE)

  results <- some_function(df)

  return(convert_to_payload(results))
}
```

It fails on the line `df <- jsonlite::parse_json(json_string, simplifyVector = TRUE)`

If anyone could help, this would be greatly appreciated.

**Comment by jeroen** [comment]
You must have messed up your json installation during an upgrade. You need to reinstall the jsonlite package.

Close all your R sessions, then start a new, clean R and run: `install.packages("jsonlite")`

**Comment by mudgalsaurabh** [comment]
thanks I  had same issue and resolved after installing "jsonlite"
