### ISSUE TITLE
Supporting mixed type JSON

### ISSUE THREAD

**Issue by JunaidMB** [jeroen/jsonlite#310]
Hello,

I'm using the jsonlite package to create the body of an HTTP request to a machine learning model deployed as a webservice. The request to the webservice (deployed on IBM Cloud) takes the following JSON object as a body

``` {"fields":["checking_balance","months_loan_duration","credit_history","purpose","amount","savings_balance","employment_length","installment_rate","personal_status","other_debtors","residence_history","property","age","installment_plan","housing","existing_credits","dependents","telephone","foreign_worker","job"],"values":[["&lt; 0 DM",6,"critical","radio/tv",1169,"unknown","&gt; 7 yrs",4,"single male","none",4,"real estate",67,"none","own",2,1,"yes","yes","skilled employee"]]}) ```

Where the fields are model input features and the values are the values of the input features sent to be scored by the model. I want to replicate the above JSON object through R. I've gotten close with the following:

toJSON(list(
    fields = c("checking_balance","months_loan_duration","credit_history","purpose","amount","savings_balance","employment_length","installment_rate","personal_status","other_debtors","residence_history","property","age","installment_plan","housing","existing_credits","dependents","telephone","foreign_worker","job")
    ,values = list(c("&lt; 0 DM",6,"critical","radio/tv",1169,"unknown","&gt; 7 yrs",4,"single male","none",4,"real estate",67,"none","own",2,1,"yes","yes","skilled employee"))))

which produces the following JSON object 

``` {"fields":["checking_balance","months_loan_duration","credit_history","purpose","amount","savings_balance","employment_length","installment_rate","personal_status","other_debtors","residence_history","property","age","installment_plan","housing","existing_credits","dependents","telephone","foreign_worker","job"],"values":[["&lt; 0 DM","6","critical","radio/tv","1169","unknown","&gt; 7 yrs","4","single male","none","4","real estate","67","none","own","2","1","yes","yes","skilled employee"]]} ```

This is very close but the integers in the values section are converted to characters. 

Is there a way to construct/ cast a list as a JSON so that the numbers and characters retain their types? I'm aware that inside the list I am using an atomic vector and atomic vectors cannot mix types in R. I was wondering if there is a way around this or a method I haven't thought of. Any help would be much appreciated.

**Comment by jeroen** [comment]
You can put them in a list and use `unbox()` or `auto_unbox=TRUE` like so:

```r
x <- list(TRUE, "foo", 123)
jsonlite::toJSON(x, auto_unbox=TRUE)
# [true,"foo",123]
```

**Comment by JunaidMB** [comment]
That's done it - thank you! :)
