### ISSUE TITLE
Feature request: JSON references

### ISSUE THREAD

**Issue by samssann** [jeroen/jsonlite#319]
https://json-spec.readthedocs.io/reference.html

A JSON Reference is a mapping with a unique key $ref, which value is a JSON Pointer. For example, this object:
```
{
  "foo": {"$ref": "#/bar"},
  "bar": true
}
```
Can be resolved as:
```
{
  "foo": true,
  "bar": true
}
```

**Comment by jeroen** [comment]
This is not in the scope of jsonlite. You could implement this in a separate package that builds on jsonlite to parse, and then resolves the references.
