### ISSUE TITLE
toJSON fails to preserve name of named entities in a list

### ISSUE THREAD

**Issue by aminadibi** [jeroen/jsonlite#320]
toJSON seems to lose the name of named elements inside a list. Problem is that second order names will be lost in api calls:

```
> test <- list(
+    a = c(boz = 2, qale = 4),
+    b = 5
+ )
> 
> test
$a
 boz qale 
   2    4 

$b
[1] 5

> 
> toJSON (test)
{"a":[2,4],"b":[5]} 
> fromJSON(toJSON(test))
$a
[1] 2 4

$b
[1] 5
```

**Comment by dcooley** [comment]
I believe this is covered in [this issue](https://github.com/jeroen/jsonlite/issues/76) where Jeroen lays out the reasons.

The solution to have named elements is to use a list

```r
test <- list(
 a = list(boz = 2, qale = 4),
 b = 5
)


jsonlite::toJSON( test )
# {"a":{"boz":[2],"qale":[4]},"b":[5]}
```

**Comment by jeroen** [comment]
There is an option `keep_vec_names` but I really recommend you use a named list instead:

```r
test <- list(
  a = list(boz = 2, qale = 4),
  b = 5
)
jsonlite::toJSON( test , keep_vec_names = T)
```
