### ISSUE TITLE
Error: lexical error: invalid char in json text.

### ISSUE THREAD

**Issue by yueliosu** [jeroen/jsonlite#331]
Hi Jeroen, 

I encountered some issues when I used the fromJSON to get some content from the url. Could you please help me figure out the issue here? How could I solve this?

Thank you,
Yue

> res = GET("https://api.gdeltproject.org/api/v2/context/context?format=html&query=masks%20&mode=artlist&format=json&maxrecords=200&STARTDATETIME=20200827000000&ENDDATETIME=20200827003000")
> #rawToChar(res$content)
> data=fromJSON(rawToChar(res$content))
Error: lexical error: invalid char in json text.
          alth.", "context": "{\/p} \\"Many Ohioans find the mask mand
                     (right here) ------^

**Comment by jeroen** [comment]
This is not your fault, there is a server bug and it seems to be generating improper json. You should contact the server and give them this example.

As a workaround you can use this:

```r
req <- httr::GET("https://api.gdeltproject.org/api/v2/context/context?format=html&query=masks%20&mode=artlist&format=json&maxrecords=200&STARTDATETIME=20200827000000&ENDDATETIME=20200827003000")
str <- rawToChar(req$content)
str <- gsub('\\\\"', '\\"', str, fixed = TRUE)
jsonlite::fromJSON(str)
```
