### ISSUE TITLE
serializeJSON and empty slots of S4 objects: cannot be serialized/unserialized

### ISSUE THREAD

**Issue by FelixErnst** [jeroen/jsonlite#332]
Hi @jeroen ,

I tripped over this snippet not working, because empty slots (`NULL`), are converted to `\001NULL\001`, which is apparently not compatible with `unserializeJSON`

```
>library(S4Vectors)
>unserializeJSON(serializeJSON(DataFrame()))
Error in initialize(value, ...) : object '\001NULL\001' not found
```
It seams a bit weird.

This is not really a use case I really want to use, but I thought I let you know. 

Felix

**Comment by jeroen** [comment]
I don't use S4 myself, why does R convert empty slots to `\001NULL001`? Is a normal in S4?

```r
x <- S4Vectors::DataFrame()
x@rownames
# NULL
attr(x, 'rownames')
# `\001NULL\001`

```

**Comment by FelixErnst** [comment]
A slot is by default empty. So it is quite a general rule, I guess. Thanks for fixing it.
