### ISSUE TITLE
Installation of jsonlite on Windows, R version 4.0.2

### ISSUE THREAD

**Issue by staci12** [jeroen/jsonlite#333]
I am having the following error when trying to install jsonlite. I have tried multiple different URLs with repos to try to fix the problem but that didn't work. 

> install.packages("jsonlite")
Installing package into ‘C:/Users/Staci Board/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.6/jsonlite_1.7.1.zip'
Warning in install.packages :
  cannot open URL 'https://cran.rstudio.com/bin/windows/contrib/3.6/jsonlite_1.7.1.zip': HTTP status was '404 Not Found'
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  cannot open URL 'https://cran.rstudio.com/bin/windows/contrib/3.6/jsonlite_1.7.1.zip'
Warning in install.packages :
  download of package ‘jsonlite’ failed

**Comment by jeroen** [comment]
There seems to be temporary syncing issue with CRAN for R 3.6. I think it will resolve itself in a few hours, maybe a day.

**Comment by jeroen** [comment]
Should be fixed now.

**Comment by staci12** [comment]
yes it is fixed! thank you
