### ISSUE TITLE
gzcon(curl("https:// xxx.json.gz )          premature EOF closing gzcon input connection

### ISSUE THREAD

**Issue by sandrineHu** [jeroen/jsonlite#335]
Hello,
As explained in the jsonlite pdf , if I want to stream in a https url, I need to use the script below (with open data json.gz file  ).
Also is explained JSON streaming is done using lines of minified JSON records, a.k.a. ndjson. I got the error message below : what happens ?

library(jsonlite)
library(curl)
s<- stream_in(gzcon(curl("https://cadastre.data.gouv.fr/data/etalab-cadastre/2020-07-01/geojson/departements/09/cadastre-09-parcelles.json.gz")))
# parse error: premature EOF closing gzcon input connection

or 

s<- stream_in(gzcon(pipe("curl https://cadastre.data.gouv.fr/data/etalab-cadastre/2020-07-01/geojson/departements/09/cadastre-09-parcelles.json.gz")))
#premature EOF closing gzcon input connection

Thanks
Sandrine

**Comment by jeroen** [comment]
`stream_in` handles jsonlines data, but your data is geojson. You probably need to extract the file and use the `sf` package.

```r
library(sf)
data <- read_sf("~/Downloads/cadastre-09-parcelles.json")
```
