### ISSUE TITLE
stuck importang large file ( >100GB)

### ISSUE THREAD

**Issue by tridelt** [jeroen/jsonlite#345]
Hi guys!
I am trying to write a very large dataset to my database. I use the following code snippet.

```
jsonlite::stream_in(textConnection(readLines('spotify_indie_past_listings_cleaned.jsonlines')),verbose=TRUE,pagesize = 1000, handler = function(df){
  df <- data.frame(df, stringsAsFactors=FALSE)
  dbWriteTable(con, filename, df, overwrite=FALSE,append=TRUE, row.names=FALSE, field.types=past_types)
})
```

I have previously had success importing files with 30GB. 

Nevertheless, a lot of people online seem to suggest to directly import it into the database with the database's CLI, but I don't see the need for that I can just stream it with jsonlines. However, I am now wondering if 100GB is too large maybe even for jsonlite or am I using this package incorrectly?

The code freezes and my fear is that instead of streaming it tries to load everything into memory.
Would love to hear from you.
Yours,
tridelt

**Comment by jeroen** [comment]
I think you need to remove the readLines part:

```r
jsonlite::stream_in(file('spotify_indie_past_listings_cleaned.jsonlines'), verbose=TRUE, handler = function(df){
  df <- data.frame(df, stringsAsFactors=FALSE)
  dbWriteTable(con, filename, df, overwrite=FALSE,append=TRUE, row.names=FALSE, field.types=past_types)
})
```

**Comment by tridelt** [comment]
thank you that's was it!!!!!
