### ISSUE TITLE
Hardcoded 15 significant digits in num_to_char.c

### ISSUE THREAD

**Issue by cat-zeppelin** [jeroen/jsonlite#350]
Accordingly to Standard for Floating-Point Arithmetic (IEEE754) if a double-precision number converted to string with 17 significant digits and then converted back to double-precision representation, the final result must match the original number.

But unfortunatelly in numerous places in num_to_char.c (e.g. row 30
`int sig_digits = signif ? ceil(fmin(15, precision)) : 0;)`
) the number of significant digits limited to 15, so that it is impossible to serialize a double precision number to json and deserialize it to the original value.

**Comment by jeroen** [comment]
> Accordingly to Standard for Floating-Point Arithmetic (IEEE754) if a double-precision number converted to string with 17 significant digits and then converted back to double-precision representation, the final result must match the original number.

Great, but that is not the purpose of json. If you want to retain the full precision of a double you better use a binary format, for example you can have a look at `protolite::serialize_pb()`. JSON is light weight human readable text format.

**Comment by cat-zeppelin** [comment]
I can not agree that changing 15 digits to 17 can affect "human-readibility". On the other hand it allows to preciselly represent double precision values still in human readble format accordingly to the Standard so that converting to json and back will give the same number which might be importand e.g. for plumber services which sometimes also use JSON as interchange format.
In any case I can not insist on changing this so if you don't want to change 15 to 17 it's obviously your decision and everyone can rebuild the package localy with any desired changes.
Just in case (as Eng is not my native lang), no negative message here. Thanks for the great package.

**Comment by jeroen** [comment]
I think I had set it to 15 because from a statististical point of view, the 16th and 17th digit may not be signfificant. For example if you print `pi` with 17 digits, you get:

```r
> print(pi, digits=17)
[1] 3.1415926535897931
```

However the actual value of PI is `3.1415926535897932`. So the last digit is an artefact of the double precision, it may not accurately reflect the actual number.

**Comment by cat-zeppelin** [comment]
I'm sorry but this argument doesn't work as well, since pi in R is defined as 4 * atan(1) (see https://github.com/wch/r-source/blob/trunk/src/library/base/R/constants.R), not as a constant with given number of digits.
`identical(pi, 3.1415926535897931)` and `identical(pi, 3.1415926535897932)` (as well as '==' instead of 'identical') both returns TRUE. 
The reason is similar to (for instnce) precision of milisiconds for datetime type in SQL Server: you can store date time with 3-value miliseconds in this type, but not with granularity of 1 millisecond because of limitation of bits for storing values.
To conclude, 16 or 17th digit for double precision values with 53-bit mantisa has the same "rights" as 4rth or 12th significant digit or any other between the 1st and the 17th.
Again, what I wanted to say is that the Standard I mentioned says that 17 digits are always enough to convert bit to decimal representation and back again without loosing any information and thus (IMHO) artifitial limitation of significant digits by 15 is not correct.

**Comment by cat-zeppelin** [comment]
And lastly, in the vignette (https://cran.r-project.org/web/packages/jsonlite/vignettes/json-aaquickstart.html) you say that 

> Thereby we can convert between R objects and JSON without loss of type or information, and without the need for any manual data munging.

which is not true

Current implementation returns FALSE for the simple check

```
json <- jsonlite::toJSON(pi, digits = I(15))
pi2 <- jsonlite::fromJSON(json)
identical(pi, pi2)
# > [1] FALSE
```

I've rebuilt the package locally with fixed 15 to 17 in num_to_char.c, and now it works as it must work. This code returns TRUE

```
json <- jsonlite::toJSON(pi, digits = I(17))
pi2 <- jsonlite::fromJSON(json)
identical(pi, pi2)
# > [1] TRUE
```

**Comment by Downchuck** [comment]
Yeah this one caught me too - I was processing some JSON from a source and it was dropping digits

```
toJSON(pi, digits=14) == toJSON(pi, digits=15)
```

**Comment by Downchuck** [comment]
@jeroen https://github.com/jeroen/jsonlite/blob/6a30acaead6539f11de19f4d02d1866d04fa5d43/src/num_to_char.c#L64

That number should at least be documented where it says: "Use NA for max precision.", the max precision is hard coded at 15. It seems that some popular library is using just a few more digits. e.g., this is what broke my tests: "1.7379807266321934".

**Comment by cat-zeppelin** [comment]
it must be 17. dot. I explaind in the thread why its wrong. for my own usage (in production) we simply rebuilt the library from source.

**Comment by Downchuck** [comment]
@cat-zeppelin Agreed 👍🏻.

@jeroen This is based on precision of the double floating point spec, where the objection commented on the code was aboit statistical validity. As Json is just based on ietf specs I think that @cat-zeppelin is correct in stating the hard coded limit of up to 14 should be raised to up to 16.
