### ISSUE TITLE
Consider using vctrs::vec_rbind for rbind_pages

### ISSUE THREAD

**Issue by hongooi73** [jeroen/jsonlite#351]
First up, thanks again for this package and all the other work you've done on R infra!

A suggestion I'd like to make: currently `rbind_pages` uses `plyr::rbind.fill` to bind the pages together. Rather than this, perhaps use `vctrs::vec_rbind` instead. This is for a few reasons:

- plyr is a rather old package and is no longer being actively updated (all the changes since 2015 have been to keep it from failing CRAN checks). It also infamously conflicts with dplyr, and requires Rcpp which is a relatively heavyweight dependency (11MB).
- By contrast vctrs is actively updated and maintained, and relatively lightweight (it has more dependencies, but they add up to barely 1/3 the size of Rcpp)
- `vec_rbind` natively supports nested data frames, unlike `rbind.fill` which must be called recursively to handle this scenario. This should simplify `rbind_pages` drastically, to the point where it becomes basically a one-liner.
- It appears fairly robust to corner cases, eg #325 isn't a problem for `vec_rbind`.

I've used `vec_rbind` myself to bind paged results together (partly because I was unaware of `rbind_pages` at the time!) and haven't encountered any problems. I can make a PR for this if you like.

**Comment by jeroen** [comment]
Yes that sounds good, can you make a pr?
