### ISSUE TITLE
Proposal for handling scalars vs. vectors in JSON serialization

### ISSUE THREAD

**Issue by chrisknoll** [jeroen/jsonlite#361]
Hello, @jeroen ,
  I understand that this topic may have been rehashed a number of times, I believe you address this concern in [your vignette](https://cran.r-project.org/web/packages/jsonlite/vignettes/json-mapping.pdf), and so I am not ignoring any of the information you present there.  

I would like to propose/request a feature of jsonlite to handle the issue of scalars being deserialized into R which then serialize into arrays in the JSON result.  `auto_unbox = T` can only take us so far. 

To put the issue I'm talking about into context, consider the following script:

```
> x0 <- jsonlite::fromJSON("{\"x\":1, \"y\":[1]}");
> jsonlite::toJSON(x0);
{"x":[1],"y":[1]} 
> jsonlite::toJSON(x0,auto_unbox = T);
{"x":1,"y":1} 
```

So, this is all expected and by design, but leaves a fundamental problem unaddress whcih is: the data came in as a scalar (ie: not an array), but is serialized out as an array, which leads to a problem if you submit it back to the server, that the datatype of [] (in java for example) is a List<>, but the datastructure says it should be an int.

I do understand why this works the way it works: in R, everything is a vector so you can't distinguish the in-memory datastructure as the 'integer is a vector' back to the json serlialized non-array form.

My proposal is to introduce a new structure in `jsonlite` called JSONScalar which behaves like a vector for any R-based operation, but when serialized out, results in the correct form (scalar) when `toJSON()` is called.  This JSONScalar would be completely transparant to the user: ie:

```
> x0 <- jsonlite::fromJSON("{\"x\":1, \"y\":[1]}");
> class(x0$x)
"integer"
> length(x0$x)
[1] 1
>x0$x[1][1][1][1][1]
[1] 1
```

but, when we serlize x0 using `toJson()`:

```
> jsonlite::toJSON(x0)
{"x":1,"y":[1]} 
> jsonlite::toJSON(x0,auto_unbox = T);
{"x":1,"y":1} 
```

In the above example: I'm leaving the auto_unbox behavior alone in the case of the `toJSON(auto_unbox = T)` since the in-memory R storage for `y` was a vector, and auto_unbox converts 1 length vectors into non-array (scalar) in JSON.  

It is my hope that if this feature is implemented, you won't have to use auto_unbox.

For creating JSON programatically, I would expect that this type of code would give the expected results:

```
> xObj <- list(x=JSONScalar(1), y=c(1));
> xObj$x[1][1][1][1]
[1] 1
> jsonlite::toJSON(xObj)
{"x":1,"y":[1]} 
```

I hope this all makes sense, and thank you for your consideration.

-Chris

**Comment by jeroen** [comment]
We have that already:

```r
x <- 123
y <- jsonlite::unbox(456)
class(x)
## [1] "numeric"
jsonlite::toJSON(list(x=x, y=y))
## {"x":[123],"y":456} 
```

**Comment by chrisknoll** [comment]
Ok, good to know, but could you tell me why it doesn't seem to be used in the example I gave:

```
> x0 <- jsonlite::fromJSON("{\"x\":1, \"y\":[1]}");
> jsonlite::toJSON(x0);
{"x":[1],"y":[1]} 
> jsonlite::toJSON(x0,auto_unbox = T);
{"x":1,"y":1} 
```

Under the covers, I would have expected the `x` field to be captured as `unbox()` or as `scalar numeric` as the `class()` since that field is not annotated as a collection via the `[]` notation.  I noticed there is a `simplifyVector` that I might be able to use so I used it in these cases:

```
> x0 <- jsonlite::fromJSON("{\"x\":1, \"y\":[1]}", simplifyVector = TRUE);
> jsonlite::toJSON(x1, auto_unbox=T);
{"x":[1],"y":[1]} 
> 
> x1 <- jsonlite::fromJSON("{\"x\":1, \"y\":[1]}", simplifyVector = FALSE);
> jsonlite::toJSON(x1, auto_unbox=T);
{"x":1,"y":[1]} 
```

So, simplifyVector seems to interact with the auto_unbox in some way that the x was left as a scalar value in the result.  This is the desired result, but I wanted to confirm that I was using `simplifyVector ` in the proper way.

I also tried this with some nested structures, and seems to get the result I want when i `simplifyVector = FALSE` and `auto_unbox = TRUE`:

```
> z0 <- jsonlite::fromJSON("{\"x\":1, \"y\":[1], \"z\": [{ \"x\": 1, \"y\": [1]}]}", simplifyVector = TRUE);
> jsonlite::toJSON(z0);
{"x":[1],"y":[1],"z":[{"x":1,"y":[1]}]} 
> jsonlite::toJSON(z0,auto_unbox = T);
{"x":1,"y":1,"z":[{"x":1,"y":1}]} 
> 
> 
> z1 <- jsonlite::fromJSON("{\"x\":1, \"y\":[1], \"z\": { \"x\": 1, \"y\": [1]}}", simplifyVector = FALSE);
> jsonlite::toJSON(z1);
{"x":[1],"y":[[1]],"z":{"x":[1],"y":[[1]]}} 
> jsonlite::toJSON(z1,auto_unbox = T);
{"x":1,"y":[1],"z":{"x":1,"y":[1]}} 
> 
> 
> z3 <- jsonlite::fromJSON("{\"x\":1, \"y\":[1], \"z\": [{ \"x\": 1, \"y\": [1]}]}", simplifyVector = TRUE);
> jsonlite::toJSON(z3);
{"x":[1],"y":[1],"z":[{"x":1,"y":[1]}]} 
> jsonlite::toJSON(z3,auto_unbox = T);
{"x":1,"y":1,"z":[{"x":1,"y":1}]} 
> 
> z4 <- jsonlite::fromJSON("{\"x\":1, \"y\":[1], \"z\": [{ \"x\": 1, \"y\": [1]}]}", simplifyVector = FALSE);
> jsonlite::toJSON(z4);
{"x":[1],"y":[[1]],"z":[{"x":[1],"y":[[1]]}]} 
> jsonlite::toJSON(z4,auto_unbox = T);
{"x":1,"y":[1],"z":[{"x":1,"y":[1]}]}
```

So the combination of `simplifyVector = F` and `auto_unbox = T` seems to get the result that I want, but I wanted to make sure I wasn't overlooking something important.  I think it's also worth noting that in your example, simplifyVector and auto_unbox were not set to get the result:

```
x <- 123
y <- jsonlite::unbox(456)
class(y)
## [1] "scalar"  "numeric"
jsonlite::toJSON(list(x=x, y=y))
## {"x":[123],"y":456} 
```

So when creating the object programmatically, I have to be careful of using the right settings in this case.

**Comment by chrisknoll** [comment]
Hi, I'm back again, after playing further, I noticed that when `simplifyVector` is FALSE, array elements are actually arrays-of-arrays in the parsed value.  Ie:
```
> x0 <- jsonlite::fromJSON("{\"x\":1, \"y\":[1]}", simplifyVector = F);
> jsonlite::toJSON(x0);
{"x":[1],"y":[[1]]} 
```

Since unbox() does exist, I would like to alter my proposal to make `jsonlite.fromJSON()` call `unbox()` on single-element JSON elements so that they are 'marked' as `scalar` when they come out of the JSON such that when they get serialized back into JSON, they are properly wrapped in `[]` (or not, as the case may be).

It seems unbox() does exactly what I want:

```
> x<-jsonlite::unbox(1)
> length(x)
[1] 1
> x
[x] 1
> x[1]
[1] 1
> x[1][1][1][1]
[1] 1
```

So x behaves just like any other vector type.   My only issue is that I wish that `fromJSON` applied it.  Could a param of something like `unbox = TRUE` be added to `fromJson()` such that non-array elements are marked as singletons?  That is essentially the difference between using `[]` in JSON vs a direct value.

**Comment by jeroen** [comment]
I'm sorry this sounds very complicated and messy, and I don't think this weighs up to the benefits, if any.

**Comment by chrisknoll** [comment]
Thanks for the feedback.  I'm sorry that you don't see the benefit of it, I think it's very beneficial for a fromJSON() to result in the same structure that was read from toJSON() but perhaps you haven't seen that use case (but I'm sure others have, based on my search for workarounds for this behavior).

In case anyone is interested (and has the necessary C programing background and familiarity with the YAJL parser), I've narrowed down a potential fix to these lines ([here ](https://github.com/jeroen/jsonlite/blob/6a30acaead6539f11de19f4d02d1866d04fa5d43/src/parse.c#L86)or [here](https://github.com/jeroen/jsonlite/blob/6a30acaead6539f11de19f4d02d1866d04fa5d43/src/parse.c#L105)) where it might be possible to capture the information about the JSON node (ie: it is an array) so that it can be handled in the R-code.

From what I can tell, the issue is that when YAJL parses (in C), we lose information about if the node was an array or not, and when the R objects are created (in C), we don't know if that element in the resulting R list was an array.  Without that information, all that can be done is to make a 'guess' as to the nature of the JSON element based on if it is a vector of length 1 or not.  With the necessary changes to the C code, I believe it would be possible to capture this meta-information about the element, and then provide a handler on the R side to unbox() it in from JSON, if desired.

**Comment by darabos** [comment]
This issue is fantastically useful, thank you both! I haven't seen `unbox` and `auto_unbox` documented anywhere. (Neither in the vignettes nor on Arxiv.)

**Comment by ablack3** [comment]
How about this? 
``` r
input <- "{\"x\":1,\"y\":[1]}"
x0 <- jsonlite::fromJSON(input, simplifyVector = F)
output <- jsonlite::toJSON(x0, auto_unbox = T)

cat(input)
#> {"x":1,"y":[1]}
cat(output)
#> {"x":1,"y":[1]}

input == output
#> [1] TRUE
```

<sup>Created on 2023-09-13 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
