### ISSUE TITLE
Segmentation fault when using pretty=TRUE

### ISSUE THREAD

**Issue by david-cortes** [jeroen/jsonlite#366]
I'm experiencing a segmentation fault when converting an R list to JSON with `pretty=TRUE`. Attached is an Rds file which causes the crash (ignore the extension name, GH won't allow arbitrary file uploads).

Code to reproduce the problem:
```r
lst <- readRDS("list_crash.zip")
jsonlite::toJSON(lst, pretty=TRUE)
```
[list_crash.zip](https://github.com/jeroen/jsonlite/files/7026110/list_crash.zip)

ASAN points to the following culprit:
```
==707==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6020000183b1 at pc 0x7ff71ff685ce bp 0x7ffdc07fbd40 sp 0x7ffdc07fb4e8
WRITE of size 2 at 0x6020000183b1 thread T0
    #0 0x7ff71ff685cd in __interceptor_memcpy (/usr/lib/x86_64-linux-gnu/libasan.so.6+0x3a5cd)
    #1 0x7ff713cfb5f0 in append_text /tmp/RtmpRY2Etg/R.INSTALL297d307467/jsonlite/src/collapse_pretty.c:15
    #2 0x7ff713cfbea1 in C_collapse_array_pretty_inner /tmp/RtmpRY2Etg/R.INSTALL297d307467/jsonlite/src/collapse_pretty.c:116
```

Version: 1.7.2, installed from CRAN, issue reproduced using the RDsan build from https://github.com/wch/r-debug

**Comment by jeroen** [comment]
Thanks. I also see this in RDsan

```r
RDsan -e 'jsonlite::toJSON(integer(0), pretty=T)'
```

**Comment by jeroen** [comment]
Thanks, looks like this was a real bug. Unbelievable this has not come up before.

**Comment by jeroen** [comment]
jsonlite 1.7.3 is on CRAN now with this fix.
