### ISSUE TITLE
Bug when parsing "[A, B, C]"

### ISSUE THREAD

**Issue by sebffischer** [jeroen/jsonlite#370]
The string "[A, B, C]" is a valid JSON string as can be verified [here](https://jsononline.net/json-validator). 

However 

`jsonlite::fromJSON("[A, B, C"]`

gives the error: 
`unexpected character 'A'`

**Comment by jeroen** [comment]
No it's not valid JSON. However if you include the double quotes in your validator webpage, it parses the entire thing as a single string instead of JSON
