### ISSUE TITLE
Boxing more flexible

### ISSUE THREAD

**Issue by dokato** [jeroen/jsonlite#371]
Is there a way to force jsonlite to keep single elements in boxes in one place and not in the other:, for example:

```r
jsonlite::write_json(
  list(a = jsonlite::unbox(as.character(123)),
       b = list("id" ="label",
                "types"= c(1,2,3)
       )
       ),
  "test.json",
  auto_unbox = F,
)
```

That gives:

```
{"a":"123","b":{"id":["label"],"types":[1,2,3]}}
```

But I want:

```
{"a":"123","b":[{"id":["label"],"types":[1,2,3]}]}
```

Maybe something opposite to `unbox`, like `box` to force that?

**Comment by jefferis** [comment]
If I understand correctly, you can use`I()` to wrap the single elements that you don't want to be unboxed.

**Comment by jefferis** [comment]
Example here:

https://github.com/natverse/fafbseg/blob/e51d48e78caa6721762b6755702c8e2d022d190b/R/urls.R#L185-L196

**Comment by dokato** [comment]
Thanks @jefferis , it doesn't seem to work on lists though. What I want is a single list wrapped in square brackets, i.e. `[{"id":["label"],"types":[1,2,3]}]`.

```r
jsonlite::write_json(
  list(a = jsonlite::unbox(as.character(123)),
       b = I(c(list("id" ="label",
                "types"= c(1,2,3)
       )
       ))
  ),
  "test.json",
  auto_unbox = F
)
```

**Comment by jeroen** [comment]
`I()` is only used icw `auto-unbox=T`. But it sounds like you want to wrap your list in another list?

```r
jsonlite::toJSON(
  list(a = jsonlite::unbox(as.character(123)),
       b = list(list("id" ="label",
                "types"= c(1,2,3)
       )
       ))
)
```

**Comment by dokato** [comment]
That's it, cheers @jeroen! But still it's a bit counterintuitive. I'd expect another list to add curly brackets rather than square here. I'd still suggest introducing `box` to API to handle this.

**Comment by jeroen** [comment]
Named lists become {} and unnamed lists become []. It's all in the docs :)
