### ISSUE TITLE
Messages when loading blob and jsonlite

### ISSUE THREAD

**Issue by krlmlr** [jeroen/jsonlite#373]
```
      Found more than one class "blob" in cache; using the first, from namespace 'blob'
      Also defined by 'jsonlite'
```

See e.g. https://github.com/cynkra/dm/pull/745/files#diff-7d82583ffca8693518bbd7850f257dc85176e3b79287e7bcb2388665d0c25aaeR6 .

Not sure how to trigger it. Most likely caused by 927cf6ef6262733ecfd6124780b2de08db91f27e.

Perhaps you could call `setMethod()` lazily, when the blob package is loaded?

**Comment by jeroen** [comment]
Can we try to find a small reprex for this warning because I am not seeing it. This will likely also trigger the original warning.

**Comment by jeroen** [comment]
Reprex for current message:

```r
library(blob)
library(jsonlite)
getClassDef("blob")
## Found more than one class "blob" in cache; using the first, from namespace 'blob'
## Also defined by ‘jsonlite’
```

**Comment by hannes101** [comment]
Just for reference, there's a stackoverflow question on that error.

**Comment by mkoohafkan** [comment]
Is it safe to ignore this warning, or should I revert to an earlier version of `jsonlite`? I notice that `tidyverse` now depends on `jsonlite v1.7.2`, which I'm guessing is where this issue was created (blob class is mentioned in the NEWS).

**Comment by jeroen** [comment]
It is safe to ignore. I'll push out another release to fix the warning.

**Comment by jeroen** [comment]
I think I understand the problem now: Both `blob` and `jsonlite` were calling `setOldClass`, however with a different class definition. jsonlite was using

```r
setOldClass("jsonlite")
```

And blob is setting

```r
setOldClass(c("blob", "vctrs_list_of", "vctrs_vctr"))
```

I suppose that is what triggered the warning, and why we don't see the warning for other packages that use `setOldClass()`

**Comment by krlmlr** [comment]
Yes, of course -- I completely missed that, sorry.

**Comment by krlmlr** [comment]
Thanks, fixed now.
