### ISSUE TITLE
`parse_json()` and `prettify()`, etc. cannot handle Unicode `\u0001`

### ISSUE THREAD

**Issue by zenggyu** [jeroen/jsonlite#377]
Hi, thanks for the great package!

I just found that functions such as `parse_json()` and `prettify()`, `minify()`, etc. cannot handle invisible Unicode characters such as `\u0001`, `\u0002`, etc.

Reprex below:

``` r
library(jsonlite)

json <- '{"text": "\u0001"}'

writeLines(json, "example.json")

read_json("example.json")
#> Error in parse_con(txt, bigint_as_char): lexical error: invalid character inside string.
#>                               {"text": ""} 
#>                      (right here) ------^
parse_json(json)
#> Error: lexical error: invalid character inside string.
#>                               {"text": ""}
#>                      (right here) ------^
prettify(json)
#> Error: lexical error: invalid character inside string.
#>                               {"text": ""}
#>                      (right here) ------^
```

<sup>Created on 2022-02-11 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

If such characters are illegal to valid json, can we add an option to the functions to deal with them (e.g., convert `'\u0001'` to `'\\u0001'` before parsing)?

**Comment by jeroen** [comment]
jsonlite deals fine with unicode characters:

```r
x = '{"turtle": "🐢"}'
fromJSON(x)$turtle
```

But what are talking about are control characters, those are not supposed to be in json. Therefore `toJSON` will indeed escape those:

```r
str = 'foo\001bar'
out <- toJSON(str)
fromJSON(str)
```

But jsonlite cannot help you if your input json is invalid. If your input unocde is escaped properly it works:

```r
json <- '{"text": "\\u0001"}'
fromJSON(json)$text
```
