### ISSUE TITLE
Do we (still) need to call setOldClass() ?

### ISSUE THREAD

**Issue by jeroen** [jeroen/jsonlite#378]
jsonlite uses an internal S4 generic `asJSON` to define json methods for data types:

https://github.com/jeroen/jsonlite/blob/d9200bf7b227bff49f9e6ec7fcf3d5b089a3a927/R/asJSON.AAAgeneric.R#L1-L3

When we create an `asJSON` method for an S3 class, I always first call `setOldClas` and then define the method, e.g.:

https://github.com/jeroen/jsonlite/blob/6a30acaead6539f11de19f4d02d1866d04fa5d43/R/asJSON.sf.R#L2-L3

This was mostly copied from RJSONIO, a long time ago, but I am not sure if this is still needed. New versions of R actually give a message if there are multiple packages calling `setOldClass` for the same class, for example with blob: https://github.com/jeroen/jsonlite/issues/373. 

```make
# in R 4.1
Found more than one class "blob" in cache; using the first, from namespace 'blob'
Also defined by 'jsonlite'
```

Hence we now removed `setOldClass("blob")` from jsonlite. Old versions (at least 3.6) now give the opposite warning:

```make
# In R 3.6
in method for ‘asJSON’ with signature ‘"blob"’: no definition for class “blob”
```

Because we have many more uses of `setOldClass` it would be good to figure out if when we really need this. 

An important detail is that jsonlite does not actually depend on the packages that implement S3 methods for those classes, such as `blob` or `sf`. Because S3 does not declare formal class definitions, this is not needed and undesired. In fact it should work even without those packages being installed:

```r
# create a blob object without the blob package
blob <- structure(list(raw(3), raw(3)), class = c("blob", "list"))
jsonlite::toJSON(blob)
```

From what I can tell, jsonlite passes all tests, also with old versions of R, regardless of whether we do or do not call `setOldClass`. So that begs the question if we really need this at all.

Is my understanding correct that `setOldClass` does not change any behaviour, and should best only be used on R < 4.0 to fix the message that warns `no definition for class “foo”`? Or is there more to it?

**Comment by jeroen** [comment]
Created a PR to remove the use of setOldClass for R 4.0+: https://github.com/jeroen/jsonlite/pull/379

It is still unclear to my why this problem started surfacing now, and if setOldClass was actually needed before? I can't find any changes in R that would have caused this change.

**Comment by hpages** [comment]
Hi @jeroen ,

I've not looked at this for a while but I remember it used to be the case that you need to call `setOldClass()` if you want to define S4 methods for an S3 class. IIRC that was only to avoid some gentle warnings at installation time. We actually do this in **BiocGenerics** for a few S3 classes defined in base R: https://github.com/Bioconductor/BiocGenerics/blob/master/R/S3-classes-as-S4-classes.R

Maybe it's no longer needed and we should be able to get rid of this, don't know, would need to investigate a bit more.

H.

**Comment by lawremi** [comment]
`setOldClass()` is necessary to define the inheritance structure of an S3 "class". I think the method dispatch logic is based on the first element of the `class()` vector, so if the inheritance structure is not defined, dispatch will not behave as expected. In this case, there is apparently no inheritance, so it may not be necessary. Hard to say for sure though.

**Comment by jeroen** [comment]
OK so as I understand it now, `setOldClass(x)` where x is of length 1 is a no-op, because there is no inheritance defined. Hence in the example above there is only one example where we actually define an inheritance, which is:

```
setOldClass(c("hms", "difftime"))
```

However we do not define any `asJSON` method for `difftime` so there is no need to formally declare this inheritance.
