### ISSUE TITLE
jsonlite::validate() issue with numbers as character string

### ISSUE THREAD

**Issue by elliliao** [jeroen/jsonlite#384]
Hi! I was wondering if the following is expected behavior:

```
> jsonlite::validate("100")
[1] TRUE

> jsonlite::validate("100.00")
[1] TRUE

> jsonlite::validate("asdf")
[1] FALSE
attr(,"offset")
[1] 1
attr(,"err")
[1] "lexical error: invalid char in json text.\n                                       asdf\n                     (right here) ------^\n"
```

For context, I'm using the `jsonlite::validate()` function to check whether a character string pulled from a database is a valid JSON string and seem to be encountering issues with integers that are stored as text in the database.

**Comment by jeroen** [comment]
Yes that is expected. Primitives are also json, but strings need to be quoted. 

```r
> jsonlite::validate('"asdf"')
[1] TRUE
```
