### ISSUE TITLE
NA_*_ mis-encoded as the string "NA"

### ISSUE THREAD

**Issue by r2evans** [jeroen/jsonlite#393]
```r
jsonlite::toJSON(list(
  lgl=NA, int=NA_integer_, flt=NA_real_, cpx=NA_complex_,
  chr=NA_character_, dat=Sys.Date()[NA], psx=Sys.time()[NA]
))
# {"lgl":[null],"int":["NA"],"flt":["NA"],"cpx":["NA"],"chr":[null],"dat":[null],"psx":[null]} 
```

I expect all should be the json literal `null`, not the string `"NA"`.

<details><summary><code>sessionInfo</code></summary>

```r
sessionInfo()
# R version 4.1.2 (2021-11-01)
# Platform: x86_64-w64-mingw32/x64 (64-bit)
# Running under: Windows 10 x64 (build 22000)
# Matrix products: default
# locale:
# [1] LC_COLLATE=English_United States.1252 
# [2] LC_CTYPE=English_United States.1252   
# [3] LC_MONETARY=English_United States.1252
# [4] LC_NUMERIC=C                          
# [5] LC_TIME=English_United States.1252    
# attached base packages:
# [1] stats     graphics  grDevices utils     datasets  methods   base     
# other attached packages:
# [1] r2_0.9.14
# loaded via a namespace (and not attached):
#  [1] compiler_4.1.2  fastmap_1.1.0   cli_3.3.0       tools_4.1.2    
#  [5] htmltools_0.5.2 rmarkdown_2.11  knitr_1.36      jsonlite_1.7.2 
#  [9] xfun_0.29       digest_0.6.28   rlang_1.0.2     evaluate_0.14  
```

</details>

**Comment by arnejohannesholmin** [comment]
I am also struggling to understand how jsonlite::toJSON() treats NAs. From the documentation (?jsonlite::toJSON) it is stated that there are only two options for the `na` argument; "null" and "string". However, when `na` is not specified, jsonlite::toJSON() seems to apply a third option, where you get a mixture of null and "NA", as seen in [r2evans](https://github.com/r2evans) example. 

The description of the `na` argument states the following: "how to print NA values: must be one of 'null' or 'string'. Defaults are class specific". I guess that "Defaults are class specific" is what we see here, but i still find it confusing, as I would expect either all `null` or all `NA`. 

The solution is anyhow to specify the `na` argument.

```
l <- list(
  lgl=NA, int=NA_integer_, flt=NA_real_, cpx=NA_complex_,
  chr=NA_character_, dat=Sys.Date()[NA], psx=Sys.time()[NA]
)

jsonlite::toJSON(l)
# {"lgl":[null],"int":["NA"],"flt":["NA"],"cpx":["NA"],"chr":[null],"dat":[null],"psx":[null]} 
jsonlite::toJSON(l, na = "null")
# {"lgl":[null],"int":[null],"flt":[null],"cpx":[null],"chr":[null],"dat":[null],"psx":[null]} 
jsonlite::toJSON(l, na = "string")
# {"lgl":["NA"],"int":["NA"],"flt":["NA"],"cpx":["NA"],"chr":["NA"],"dat":["NA"],"psx":["NA"]} 
```

**Comment by jeroen** [comment]
Did you read https://cran.r-project.org/web/packages/jsonlite/vignettes/json-mapping.pdf ?

**Comment by r2evans** [comment]
Sorry, Jeroen, I had skimmed through that and other docs but skipped over this part.

```
For this reason, jsonlite uses the following defaults:
• Missing values in non-numeric vectors (logical, character) are encoded as null.
• Missing values in numeric vectors (double, integer, complex) are encoded as strings
```

While I personally disagree with the split convention (preferring a single conversion), it is clearly documented (and consistently controlled with `na="null"` or `na="string"`). (By disagreeing, I'm not saying it's a trivial thing, to be clear: JSON has but one form of "emptiness" which is not in concert with R's semantics. There has to be some expectation of "loss of specificity", hoping the reading end will disambiguate the translation correctly.)

Thanks for the reminder and for the package.
