### ISSUE TITLE
jsonc (JSON with comments) support

### ISSUE THREAD

**Issue by hongooi73** [jeroen/jsonlite#394]
Hi,

I've got a bunch of jsonc (JSON with comments) files that I need to process. jsonlite succeeds in reading them, but I also have to write out jsonc, and I don't think there's a way to write comments.

The files basically look like

```jsonc
{
  /* here is some stuff about 'a' */
  "a": 1,
  /* here is some stuff about 'b' */
  "b": 2,
  /* etc */
}
```

I wonder if it would be worthwhile extending jsonlite to support creating such files? Barring that, would you know of any R package that can do this?

**Comment by jeroen** [comment]
This is out of scope for jsonlite, but you can try to use the V8 package to parse it as JavaScript and then convert to json, e.g.

```r
str <- '{
  /* here is some stuff about a */
  "a": 1,
  /* here is some stuff about b */
  "b": 2,
  /* etc */
}'

ctx <- V8::v8()
ctx$call('JSON.stringify', V8::JS(str))

```
