### ISSUE TITLE
spaces and parenthesis in Json Keys names converted to dots. 

### ISSUE THREAD

**Issue by jobouJP** [jeroen/jsonlite#419]
When converting a Json file to a dataset, is there a way to avoid spaces and parenthesis to be replaced by dots when they are converted to dataset column names.
For exemple  "EC50 (nM)"  is converted to EC50..nM.

**Comment by jeroen** [comment]
I don't think jsonlite does this, but I think it happens to your data before you feed it to jsonlite. You probably want to set `check.names = F` when creating your data frame.

```r
library(jsonlite)
df = data.frame("EC50 (nM)" = 123, check.names = F)
toJSON(df)
[{"EC50 (nM)":123}] 
```

If it happens in jsonlite, please include example code.

**Comment by jobouJP** [comment]
> I don't think jsonlite does this, but that it happens when you create the data frame. You probably want to set `check.names = F` when creating your data frame.
> 
> ```r
> library(jsonlite)
> df = data.frame("EC50 (nM)" = 123, check.names = F)
> toJSON(df)
> ## [{"EC50 (nM)":123}] 
> ```
> 
> If it happens in jsonlite, please include example code.

It happens with fromJSON not with toJSON.  when using this code :
`dataTable <- type.convert(as.data.frame(fromJSON(input$dataIn)),as.is = TRUE)`

The Json file is created in my browser using javascript and it looks like the one you showed. Just in case I also tried this:
## [{"`EC50 (nM)`":123}]
But that also did not work.

**Comment by jeroen** [comment]
You probably need to pass `check.names = F` to your `as.data.frame()` command.

**Comment by jobouJP** [comment]
Thanks
