### ISSUE TITLE
Error (data_api.R#313): lexical error: invalid char in json text.

### ISSUE THREAD

**Issue by davidmacolisa** [jeroen/jsonlite#425]
Hi All, I have quite a similar issue:

elec.bulk.api.json <- jsonlite::fromJSON(elec.bulk.api.char, flatten = TRUE)

Error (data_api.R#313): lexical error: invalid char in json text.
PK���Ã³}&WG2Â¾0{�â€ºN�JELE
(right here) ------^

I am trying to parse a character vector to json format but I get this error. Can someone help me with this? Appreciate

**Comment by jeroen** [comment]
This means your `elec.bulk.api.char` object does not contain json data.
