### ISSUE TITLE
Please enable usage of system yajl library

### ISSUE THREAD

**Issue by tillea** [jeroen/jsonlite#430]
Hi,
the Debian packaged version of jsonlite R package received a [bug report](https://bugs.debian.org/1039082) that it includes a patched code copy of the yajl library.  It would be great if your code copy would not include patches so we could build the Debian package against the Debian packaged library.
Kind regards, Andreas.

**Comment by jeroen** [comment]
Hi,

As I'm pretty sure I indicated earlier, upstream libyajl is unmaintained and we use a modified fork of the libyajl code. Therefore it is not possible to use Debian's libyajl.

The best I can offer is rename our bundled fork to something else, such that it is clear that this is a different library now.

**Comment by tillea** [comment]
Hi Jeroen,

Am Thu, Oct 26, 2023 at 11:35:34AM -0700 schrieb Jeroen Ooms:
> As I'm pretty sure I indicated earlier, upstream libyajl is unmaintained and we use a modified fork of the libyajl code. Therefore it is not possible to use Debian's libyajl.

Thanks for the (may be repeatet, sorry if I forgot).  I've tagged the according bug `wontfix` to not forget again.
 
> The best I can offer is rename our bundled fork to something else, such that it is clear that this is a different library now.

I do not think that this changes anything relevant.
Kind regards, Andreas.
