### ISSUE TITLE
Question: Pass-through of character vectors of valid json in toJSON()?

### ISSUE THREAD

**Issue by thohan88** [jeroen/jsonlite#439]
First of all, thank you so much for the excellent `jsonlite`-package.

I often deal with JSON-objects as large strings from databases such as this minimal example:

``` r
example <- data.frame(
  foo = c("bar", "bar"),
  json = c('{"foo": "bar"}', '{"foo": "bar"}') 
)
example
#>   foo           json
#> 1 bar {"foo": "bar"}
#> 2 bar {"foo": "bar"}
```

Naturally, if I convert this through `toJSON()` or `stream_out()`, json is outputted as a character as expected:
``` r
jsonlite::toJSON(example, pretty = TRUE)
#> [
#>   {
#>     "foo": "bar",
#>     "json": "{\"foo\": \"bar\"}"
#>   },
#>   {
#>     "foo": "bar",
#>     "json": "{\"foo\": \"bar\"}"
#>   }
#> ]
```
Usually, I need the conversion to JSON-data, so I do:
``` r
example$json <- lapply(example$json, jsonlite::fromJSON)
jsonlite::toJSON(example, auto_unbox = TRUE, pretty = TRUE)
#> [
#>   {
#>     "foo": "bar",
#>     "json": {
#>       "foo": "bar"
#>     }
#>   },
#>   {
#>     "foo": "bar",
#>     "json": {
#>       "foo": "bar"
#>     }
#>   }
#> ]
```

This works fine, but can take quite some time when the number and size of JSON-objects are large. 

Is there a simpler option here that I am not seeing, e.g. enabling a pass through of valid character vectors of json in `toJSON()`?

Thanks again!

**Comment by jeroen** [comment]
Something like this?

```r

example <- data.frame(
  foo = c("bar", "bar"),
  json = c('{"foo": "bar"}', '{"foo": "bar"}') 
)
class(example$json) <- 'json'

# json_verbatim passes through existing json strings
jsonlite::toJSON(example, json_verbatim=TRUE)

```

**Comment by thohan88** [comment]
This is exactly what i was looking for - thanks a lot for the quick response!
